
# This file is automatically generated, you probably don't want to edit this

.jmvrefs <- list(
    `snpstats`=list(
        `type`="software", 
        `author`="Moreno V, et al.", 
        `year`=2006, 
        `title`="SNPStats: analysis of association studies", 
        `publisher`="https://www.snpstats.net", 
        `url`="https://www.snpstats.net"), 
    `bioinfo`=list(
        `type`="journal", 
        `author`="Sole, X., Guino, E., Valls, J., Iniesta, R., Moreno, V.", 
        `year`=2006, 
        `title`="SNPStats: a web tool for the analysis of association studies", 
        `publisher`="Bioinformatics 22(15):1928-1929 https://doi.org/10.1093/bioinformatics/btl268", 
        `url`="https://doi.org/10.1093/bioinformatics/btl268"), 
    `tutorial`=list(
        `type`="software", 
        `author`="Moreno V", 
        `year`=2026, 
        `title`="SNPstats for jamovi \u2014 tutorial & documentation", 
        `publisher`="https://victor-moreno.github.io/SNPstats-jamovi/TUTORIAL.html", 
        `url`="https://victor-moreno.github.io/SNPstats-jamovi/TUTORIAL.html"), 
    `plinkformats`=list(
        `type`="web", 
        `author`="Chang, C. C., & Purcell, S.", 
        `title`="PLINK 1.9 file format reference: .bed, .bim, .fam, .ped, .map, .tped, .tfam\n", 
        `publisher`="www.cog-genomics.org", 
        `url`="https://www.cog-genomics.org/plink/1.9/formats"), 
    `vcfspec`=list(
        `type`="web", 
        `author`="The SAM/BCF/VCF specification working group", 
        `title`="The Variant Call Format (VCF) specification", 
        `publisher`="samtools.github.io/hts-specs", 
        `url`="https://samtools.github.io/hts-specs/VCFv4.2.pdf"))
