
# This file is automatically generated, you probably don't want to edit this

snpAnalysisOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpAnalysisOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            response = NULL,
            snps = NULL,
            covariates = NULL,
            responseType = "auto",
            subpop = FALSE,
            covDesc = FALSE,
            allFreq = FALSE,
            genoFreq = FALSE,
            hweTest = FALSE,
            ldAnalysis = FALSE,
            snpAssoc = FALSE,
            modelCodominant = FALSE,
            modelDominant = FALSE,
            modelRecessive = FALSE,
            modelOverdominant = FALSE,
            modelLogAdditive = FALSE,
            ciWidth = 95,
            haploFreq = FALSE,
            haploFreqMin = 0.01,
            haploAssoc = FALSE, ...) {

            super$initialize(
                package="SNPstats",
                name="snpAnalysis",
                requiresData=TRUE,
                ...)

            private$..response <- jmvcore::OptionVariable$new(
                "response",
                response,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..snps <- jmvcore::OptionVariables$new(
                "snps",
                snps,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"),
                default=NULL)
            private$..responseType <- jmvcore::OptionList$new(
                "responseType",
                responseType,
                options=list(
                    "auto",
                    "binary",
                    "quantitative"),
                default="auto")
            private$..subpop <- jmvcore::OptionBool$new(
                "subpop",
                subpop,
                default=FALSE)
            private$..covDesc <- jmvcore::OptionBool$new(
                "covDesc",
                covDesc,
                default=FALSE)
            private$..allFreq <- jmvcore::OptionBool$new(
                "allFreq",
                allFreq,
                default=FALSE)
            private$..genoFreq <- jmvcore::OptionBool$new(
                "genoFreq",
                genoFreq,
                default=FALSE)
            private$..hweTest <- jmvcore::OptionBool$new(
                "hweTest",
                hweTest,
                default=FALSE)
            private$..ldAnalysis <- jmvcore::OptionBool$new(
                "ldAnalysis",
                ldAnalysis,
                default=FALSE)
            private$..snpAssoc <- jmvcore::OptionBool$new(
                "snpAssoc",
                snpAssoc,
                default=FALSE)
            private$..modelCodominant <- jmvcore::OptionBool$new(
                "modelCodominant",
                modelCodominant,
                default=FALSE)
            private$..modelDominant <- jmvcore::OptionBool$new(
                "modelDominant",
                modelDominant,
                default=FALSE)
            private$..modelRecessive <- jmvcore::OptionBool$new(
                "modelRecessive",
                modelRecessive,
                default=FALSE)
            private$..modelOverdominant <- jmvcore::OptionBool$new(
                "modelOverdominant",
                modelOverdominant,
                default=FALSE)
            private$..modelLogAdditive <- jmvcore::OptionBool$new(
                "modelLogAdditive",
                modelLogAdditive,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..haploFreq <- jmvcore::OptionBool$new(
                "haploFreq",
                haploFreq,
                default=FALSE)
            private$..haploFreqMin <- jmvcore::OptionNumber$new(
                "haploFreqMin",
                haploFreqMin,
                min=0,
                max=0.5,
                default=0.01)
            private$..haploAssoc <- jmvcore::OptionBool$new(
                "haploAssoc",
                haploAssoc,
                default=FALSE)

            self$.addOption(private$..response)
            self$.addOption(private$..snps)
            self$.addOption(private$..covariates)
            self$.addOption(private$..responseType)
            self$.addOption(private$..subpop)
            self$.addOption(private$..covDesc)
            self$.addOption(private$..allFreq)
            self$.addOption(private$..genoFreq)
            self$.addOption(private$..hweTest)
            self$.addOption(private$..ldAnalysis)
            self$.addOption(private$..snpAssoc)
            self$.addOption(private$..modelCodominant)
            self$.addOption(private$..modelDominant)
            self$.addOption(private$..modelRecessive)
            self$.addOption(private$..modelOverdominant)
            self$.addOption(private$..modelLogAdditive)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..haploFreq)
            self$.addOption(private$..haploFreqMin)
            self$.addOption(private$..haploAssoc)
        }),
    active = list(
        response = function() private$..response$value,
        snps = function() private$..snps$value,
        covariates = function() private$..covariates$value,
        responseType = function() private$..responseType$value,
        subpop = function() private$..subpop$value,
        covDesc = function() private$..covDesc$value,
        allFreq = function() private$..allFreq$value,
        genoFreq = function() private$..genoFreq$value,
        hweTest = function() private$..hweTest$value,
        ldAnalysis = function() private$..ldAnalysis$value,
        snpAssoc = function() private$..snpAssoc$value,
        modelCodominant = function() private$..modelCodominant$value,
        modelDominant = function() private$..modelDominant$value,
        modelRecessive = function() private$..modelRecessive$value,
        modelOverdominant = function() private$..modelOverdominant$value,
        modelLogAdditive = function() private$..modelLogAdditive$value,
        ciWidth = function() private$..ciWidth$value,
        haploFreq = function() private$..haploFreq$value,
        haploFreqMin = function() private$..haploFreqMin$value,
        haploAssoc = function() private$..haploAssoc$value),
    private = list(
        ..response = NA,
        ..snps = NA,
        ..covariates = NA,
        ..responseType = NA,
        ..subpop = NA,
        ..covDesc = NA,
        ..allFreq = NA,
        ..genoFreq = NA,
        ..hweTest = NA,
        ..ldAnalysis = NA,
        ..snpAssoc = NA,
        ..modelCodominant = NA,
        ..modelDominant = NA,
        ..modelRecessive = NA,
        ..modelOverdominant = NA,
        ..modelLogAdditive = NA,
        ..ciWidth = NA,
        ..haploFreq = NA,
        ..haploFreqMin = NA,
        ..haploAssoc = NA)
)

snpAnalysisResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpAnalysisResults",
    inherit = jmvcore::Group,
    active = list(
        validationMsg = function() private$.items[["validationMsg"]],
        covDescGroup = function() private$.items[["covDescGroup"]],
        snpResults = function() private$.items[["snpResults"]],
        ldGroup = function() private$.items[["ldGroup"]],
        haploGroup = function() private$.items[["haploGroup"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="SNP Analysis")
            self$add(jmvcore::Html$new(
                options=options,
                name="validationMsg",
                title="",
                visible=TRUE))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    covDescTable = function() private$.items[["covDescTable"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="covDescGroup",
                            title="Covariate Descriptives")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="covDescTable",
                            title="Covariate Summary",
                            columns=list(
                                list(
                                    `name`="variable", 
                                    `title`="Variable", 
                                    `type`="text"),
                                list(
                                    `name`="level", 
                                    `title`="Level", 
                                    `type`="text"),
                                list(
                                    `name`="n", 
                                    `title`="n", 
                                    `type`="integer"),
                                list(
                                    `name`="stat", 
                                    `title`="Statistic", 
                                    `type`="text"))))}))$new(options=options))
            self$add(jmvcore::Array$new(
                options=options,
                name="snpResults",
                title="SNP Results",
                template=R6::R6Class(
                    inherit = jmvcore::Group,
                    active = list(
                        typingRate = function() private$.items[["typingRate"]],
                        allFreqTable = function() private$.items[["allFreqTable"]],
                        genoFreqTable = function() private$.items[["genoFreqTable"]],
                        hweTable = function() private$.items[["hweTable"]],
                        assocTable = function() private$.items[["assocTable"]]),
                    private = list(),
                    public=list(
                        initialize=function(options) {
                            super$initialize(
                                options=options,
                                name="undefined",
                                title="$key")
                            self$add(jmvcore::Html$new(
                                options=options,
                                name="typingRate",
                                title=""))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="allFreqTable",
                                title="Allele Frequencies",
                                visible="(allFreq)",
                                columns=list(
                                    list(
                                        `name`="allele", 
                                        `title`="Allele", 
                                        `type`="text"),
                                    list(
                                        `name`="count", 
                                        `title`="Count", 
                                        `type`="integer"),
                                    list(
                                        `name`="prop", 
                                        `title`="Proportion", 
                                        `type`="number", 
                                        `format`="zto"))))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="genoFreqTable",
                                title="Genotype Frequencies",
                                visible="(genoFreq)",
                                columns=list(
                                    list(
                                        `name`="genotype", 
                                        `title`="Genotype", 
                                        `type`="text"),
                                    list(
                                        `name`="count", 
                                        `title`="Count", 
                                        `type`="integer"),
                                    list(
                                        `name`="prop", 
                                        `title`="Proportion", 
                                        `type`="number", 
                                        `format`="zto"),
                                    list(
                                        `name`="responseStat", 
                                        `title`="Response (mean \u00B1 SE)", 
                                        `type`="text", 
                                        `visible`=FALSE))))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="hweTable",
                                title="Hardy-Weinberg Equilibrium",
                                visible="(hweTest)",
                                columns=list(
                                    list(
                                        `name`="group", 
                                        `title`="Group", 
                                        `type`="text"),
                                    list(
                                        `name`="n11", 
                                        `title`="N11", 
                                        `type`="integer"),
                                    list(
                                        `name`="n12", 
                                        `title`="N12", 
                                        `type`="integer"),
                                    list(
                                        `name`="n22", 
                                        `title`="N22", 
                                        `type`="integer"),
                                    list(
                                        `name`="n1", 
                                        `title`="N1", 
                                        `type`="integer"),
                                    list(
                                        `name`="n2", 
                                        `title`="N2", 
                                        `type`="integer"),
                                    list(
                                        `name`="pval", 
                                        `title`="P-value", 
                                        `type`="number", 
                                        `format`="zto,pvalue"))))
                            self$add(jmvcore::Table$new(
                                options=options,
                                name="assocTable",
                                title="Association with Response",
                                visible="(snpAssoc)",
                                columns=list(
                                    list(
                                        `name`="model", 
                                        `title`="Model", 
                                        `type`="text"),
                                    list(
                                        `name`="comparison", 
                                        `title`="Comparison", 
                                        `type`="text"),
                                    list(
                                        `name`="effect", 
                                        `title`="OR / \u03B2", 
                                        `type`="number"),
                                    list(
                                        `name`="ciLow", 
                                        `title`="Lower CI", 
                                        `type`="number"),
                                    list(
                                        `name`="ciHigh", 
                                        `title`="Upper CI", 
                                        `type`="number"),
                                    list(
                                        `name`="pval", 
                                        `title`="P-value", 
                                        `type`="number", 
                                        `format`="zto,pvalue"),
                                    list(
                                        `name`="globalP", 
                                        `title`="Global P", 
                                        `type`="number", 
                                        `format`="zto,pvalue"))))}))$new(options=options)))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    ldTable = function() private$.items[["ldTable"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="ldGroup",
                            title="Linkage Disequilibrium")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="ldTable",
                            title="Pairwise LD",
                            columns=list(
                                list(
                                    `name`="snp1", 
                                    `title`="SNP 1", 
                                    `type`="text"),
                                list(
                                    `name`="snp2", 
                                    `title`="SNP 2", 
                                    `type`="text"),
                                list(
                                    `name`="D", 
                                    `title`="D", 
                                    `type`="number"),
                                list(
                                    `name`="Dprime", 
                                    `title`="D'", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="r", 
                                    `title`="r", 
                                    `type`="number"),
                                list(
                                    `name`="pval", 
                                    `title`="P-value", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    haploFreqTable = function() private$.items[["haploFreqTable"]],
                    haploAssocTable = function() private$.items[["haploAssocTable"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="haploGroup",
                            title="Haplotype Analysis")
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="haploFreqTable",
                            title="Haplotype Frequencies",
                            visible="(haploFreq)",
                            columns=list(
                                list(
                                    `name`="haplotype", 
                                    `title`="Haplotype", 
                                    `type`="text"),
                                list(
                                    `name`="freq", 
                                    `title`="Frequency", 
                                    `type`="number", 
                                    `format`="zto"))))
                        self$add(jmvcore::Table$new(
                            options=options,
                            name="haploAssocTable",
                            title="Haplotype Association",
                            visible="(haploAssoc)",
                            columns=list(
                                list(
                                    `name`="haplotype", 
                                    `title`="Haplotype", 
                                    `type`="text"),
                                list(
                                    `name`="freq", 
                                    `title`="Frequency", 
                                    `type`="number", 
                                    `format`="zto"),
                                list(
                                    `name`="effect", 
                                    `title`="OR / \u03B2", 
                                    `type`="number"),
                                list(
                                    `name`="ciLow", 
                                    `title`="Lower CI", 
                                    `type`="number"),
                                list(
                                    `name`="ciHigh", 
                                    `title`="Upper CI", 
                                    `type`="number"),
                                list(
                                    `name`="pval", 
                                    `title`="P-value", 
                                    `type`="number", 
                                    `format`="zto,pvalue"))))}))$new(options=options))}))

snpAnalysisBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpAnalysisBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SNPstats",
                name = "snpAnalysis",
                version = c(1,0,0),
                options = options,
                results = snpAnalysisResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' SNP Analysis
#'
#' 
#' @param data [object Object]
#' @param response .
#' @param snps .
#' @param covariates .
#' @param responseType .
#' @param subpop .
#' @param covDesc .
#' @param allFreq .
#' @param genoFreq .
#' @param hweTest .
#' @param ldAnalysis .
#' @param snpAssoc .
#' @param modelCodominant .
#' @param modelDominant .
#' @param modelRecessive .
#' @param modelOverdominant .
#' @param modelLogAdditive .
#' @param ciWidth .
#' @param haploFreq .
#' @param haploFreqMin .
#' @param haploAssoc .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$validationMsg} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$covDescGroup$covDescTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$snpResults} \tab \tab \tab \tab \tab Results for each SNP \cr
#'   \code{results$ldGroup$ldTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$haploGroup$haploFreqTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$haploGroup$haploAssocTable} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' @export
snpAnalysis <- function(
    data,
    response,
    snps,
    covariates = NULL,
    responseType = "auto",
    subpop = FALSE,
    covDesc = FALSE,
    allFreq = FALSE,
    genoFreq = FALSE,
    hweTest = FALSE,
    ldAnalysis = FALSE,
    snpAssoc = FALSE,
    modelCodominant = FALSE,
    modelDominant = FALSE,
    modelRecessive = FALSE,
    modelOverdominant = FALSE,
    modelLogAdditive = FALSE,
    ciWidth = 95,
    haploFreq = FALSE,
    haploFreqMin = 0.01,
    haploAssoc = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("snpAnalysis requires jmvcore to be installed (restart may be required)")

    if ( ! missing(response)) response <- jmvcore::resolveQuo(jmvcore::enquo(response))
    if ( ! missing(snps)) snps <- jmvcore::resolveQuo(jmvcore::enquo(snps))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(response), response, NULL),
            `if`( ! missing(snps), snps, NULL),
            `if`( ! missing(covariates), covariates, NULL))


    options <- snpAnalysisOptions$new(
        response = response,
        snps = snps,
        covariates = covariates,
        responseType = responseType,
        subpop = subpop,
        covDesc = covDesc,
        allFreq = allFreq,
        genoFreq = genoFreq,
        hweTest = hweTest,
        ldAnalysis = ldAnalysis,
        snpAssoc = snpAssoc,
        modelCodominant = modelCodominant,
        modelDominant = modelDominant,
        modelRecessive = modelRecessive,
        modelOverdominant = modelOverdominant,
        modelLogAdditive = modelLogAdditive,
        ciWidth = ciWidth,
        haploFreq = haploFreq,
        haploFreqMin = haploFreqMin,
        haploAssoc = haploAssoc)

    analysis <- snpAnalysisClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

