
# This file is automatically generated, you probably don't want to edit this

snpImportOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpImportOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            sourceFormat = "bed",
            genoContent = "",
            variantContent = "",
            sampleContent = "",
            sourceDims = "",
            genoFilename = "",
            loadStatus = "",
            loadProblem = "",
            snpListText = "",
            snpListContent = "",
            snpListFilename = "",
            covContent = "",
            covFilename = "",
            covIdCol = "",
            emitSamples = TRUE,
            dosage = FALSE,
            filterSamples = FALSE,
            maxIndMissing = 10,
            hetSd = 0,
            applyFilters = FALSE,
            maxMissing = 10,
            minMaf = 0.01,
            hweGroup = "controls",
            hweP = 0.001,
            showSummary = FALSE,
            showProvenance = TRUE,
            openNew = FALSE, ...) {

            super$initialize(
                package="SNPstats",
                name="snpImport",
                requiresData=TRUE,
                ...)

            private$..sourceFormat <- jmvcore::OptionString$new(
                "sourceFormat",
                sourceFormat,
                default="bed",
                hidden=TRUE)
            private$..genoContent <- jmvcore::OptionString$new(
                "genoContent",
                genoContent,
                default="",
                hidden=TRUE)
            private$..variantContent <- jmvcore::OptionString$new(
                "variantContent",
                variantContent,
                default="",
                hidden=TRUE)
            private$..sampleContent <- jmvcore::OptionString$new(
                "sampleContent",
                sampleContent,
                default="",
                hidden=TRUE)
            private$..sourceDims <- jmvcore::OptionString$new(
                "sourceDims",
                sourceDims,
                default="",
                hidden=TRUE)
            private$..genoFilename <- jmvcore::OptionString$new(
                "genoFilename",
                genoFilename,
                default="")
            private$..loadStatus <- jmvcore::OptionString$new(
                "loadStatus",
                loadStatus,
                default="")
            private$..loadProblem <- jmvcore::OptionString$new(
                "loadProblem",
                loadProblem,
                default="",
                hidden=TRUE)
            private$..snpListText <- jmvcore::OptionString$new(
                "snpListText",
                snpListText,
                default="")
            private$..snpListContent <- jmvcore::OptionString$new(
                "snpListContent",
                snpListContent,
                default="",
                hidden=TRUE)
            private$..snpListFilename <- jmvcore::OptionString$new(
                "snpListFilename",
                snpListFilename,
                default="")
            private$..covContent <- jmvcore::OptionString$new(
                "covContent",
                covContent,
                default="",
                hidden=TRUE)
            private$..covFilename <- jmvcore::OptionString$new(
                "covFilename",
                covFilename,
                default="")
            private$..covIdCol <- jmvcore::OptionString$new(
                "covIdCol",
                covIdCol,
                default="")
            private$..emitSamples <- jmvcore::OptionBool$new(
                "emitSamples",
                emitSamples,
                default=TRUE)
            private$..dosage <- jmvcore::OptionBool$new(
                "dosage",
                dosage,
                default=FALSE)
            private$..filterSamples <- jmvcore::OptionBool$new(
                "filterSamples",
                filterSamples,
                default=FALSE)
            private$..maxIndMissing <- jmvcore::OptionNumber$new(
                "maxIndMissing",
                maxIndMissing,
                min=0,
                max=100,
                default=10)
            private$..hetSd <- jmvcore::OptionNumber$new(
                "hetSd",
                hetSd,
                min=0,
                max=10,
                default=0)
            private$..applyFilters <- jmvcore::OptionBool$new(
                "applyFilters",
                applyFilters,
                default=FALSE)
            private$..maxMissing <- jmvcore::OptionNumber$new(
                "maxMissing",
                maxMissing,
                min=0,
                max=100,
                default=10)
            private$..minMaf <- jmvcore::OptionNumber$new(
                "minMaf",
                minMaf,
                min=0,
                max=0.5,
                default=0.01)
            private$..hweGroup <- jmvcore::OptionList$new(
                "hweGroup",
                hweGroup,
                options=list(
                    "controls",
                    "all"),
                default="controls")
            private$..hweP <- jmvcore::OptionNumber$new(
                "hweP",
                hweP,
                min=0,
                max=1,
                default=0.001)
            private$..showSummary <- jmvcore::OptionBool$new(
                "showSummary",
                showSummary,
                default=FALSE)
            private$..showProvenance <- jmvcore::OptionBool$new(
                "showProvenance",
                showProvenance,
                default=TRUE)
            private$..openNew <- jmvcore::OptionAction$new(
                "openNew",
                openNew,
                action="open")

            self$.addOption(private$..sourceFormat)
            self$.addOption(private$..genoContent)
            self$.addOption(private$..variantContent)
            self$.addOption(private$..sampleContent)
            self$.addOption(private$..sourceDims)
            self$.addOption(private$..genoFilename)
            self$.addOption(private$..loadStatus)
            self$.addOption(private$..loadProblem)
            self$.addOption(private$..snpListText)
            self$.addOption(private$..snpListContent)
            self$.addOption(private$..snpListFilename)
            self$.addOption(private$..covContent)
            self$.addOption(private$..covFilename)
            self$.addOption(private$..covIdCol)
            self$.addOption(private$..emitSamples)
            self$.addOption(private$..dosage)
            self$.addOption(private$..filterSamples)
            self$.addOption(private$..maxIndMissing)
            self$.addOption(private$..hetSd)
            self$.addOption(private$..applyFilters)
            self$.addOption(private$..maxMissing)
            self$.addOption(private$..minMaf)
            self$.addOption(private$..hweGroup)
            self$.addOption(private$..hweP)
            self$.addOption(private$..showSummary)
            self$.addOption(private$..showProvenance)
            self$.addOption(private$..openNew)
        }),
    active = list(
        sourceFormat = function() private$..sourceFormat$value,
        genoContent = function() private$..genoContent$value,
        variantContent = function() private$..variantContent$value,
        sampleContent = function() private$..sampleContent$value,
        sourceDims = function() private$..sourceDims$value,
        genoFilename = function() private$..genoFilename$value,
        loadStatus = function() private$..loadStatus$value,
        loadProblem = function() private$..loadProblem$value,
        snpListText = function() private$..snpListText$value,
        snpListContent = function() private$..snpListContent$value,
        snpListFilename = function() private$..snpListFilename$value,
        covContent = function() private$..covContent$value,
        covFilename = function() private$..covFilename$value,
        covIdCol = function() private$..covIdCol$value,
        emitSamples = function() private$..emitSamples$value,
        dosage = function() private$..dosage$value,
        filterSamples = function() private$..filterSamples$value,
        maxIndMissing = function() private$..maxIndMissing$value,
        hetSd = function() private$..hetSd$value,
        applyFilters = function() private$..applyFilters$value,
        maxMissing = function() private$..maxMissing$value,
        minMaf = function() private$..minMaf$value,
        hweGroup = function() private$..hweGroup$value,
        hweP = function() private$..hweP$value,
        showSummary = function() private$..showSummary$value,
        showProvenance = function() private$..showProvenance$value,
        openNew = function() private$..openNew$value),
    private = list(
        ..sourceFormat = NA,
        ..genoContent = NA,
        ..variantContent = NA,
        ..sampleContent = NA,
        ..sourceDims = NA,
        ..genoFilename = NA,
        ..loadStatus = NA,
        ..loadProblem = NA,
        ..snpListText = NA,
        ..snpListContent = NA,
        ..snpListFilename = NA,
        ..covContent = NA,
        ..covFilename = NA,
        ..covIdCol = NA,
        ..emitSamples = NA,
        ..dosage = NA,
        ..filterSamples = NA,
        ..maxIndMissing = NA,
        ..hetSd = NA,
        ..applyFilters = NA,
        ..maxMissing = NA,
        ..minMaf = NA,
        ..hweGroup = NA,
        ..hweP = NA,
        ..showSummary = NA,
        ..showProvenance = NA,
        ..openNew = NA)
)

snpImportResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpImportResults",
    inherit = jmvcore::Group,
    active = list(
        instructions = function() private$.items[["instructions"]],
        notice = function() private$.items[["notice"]],
        provenance = function() private$.items[["provenance"]],
        summary = function() private$.items[["summary"]],
        openNewState = function() private$.items[["openNewState"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Import genotypes",
                refs=list(
                    "plinkformats",
                    "vcfspec"))
            self$add(jmvcore::Html$new(
                options=options,
                name="instructions",
                title="",
                clearWith=list(
                    "genoContent")))
            self$add(jmvcore::Html$new(
                options=options,
                name="notice",
                title="",
                visible=FALSE,
                clearWith=list(
                    "genoContent")))
            self$add(jmvcore::Table$new(
                options=options,
                name="provenance",
                title="Import report",
                visible="(showProvenance)",
                rows=0,
                clearWith=list(
                    "genoContent",
                    "variantContent",
                    "sampleContent",
                    "covContent",
                    "hweGroup"),
                columns=list(
                    list(
                        `name`="item", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary",
                title="SNP summary",
                visible="(showSummary)",
                rows=0,
                clearWith=list(
                    "genoContent",
                    "variantContent",
                    "sampleContent",
                    "hweGroup"),
                columns=list(
                    list(
                        `name`="snp", 
                        `title`="SNP", 
                        `type`="text"),
                    list(
                        `name`="chr", 
                        `title`="Chr", 
                        `type`="text"),
                    list(
                        `name`="bp", 
                        `title`="Position", 
                        `type`="number", 
                        `format`=".0f"),
                    list(
                        `name`="alleles", 
                        `title`="Alleles (A/B)", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="missing", 
                        `title`="Missing", 
                        `type`="integer"),
                    list(
                        `name`="maf", 
                        `title`="MAF", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="genoCounts", 
                        `title`="AA / AB / BB", 
                        `type`="text"),
                    list(
                        `name`="hwePval", 
                        `title`="HWE p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="allele", 
                        `title`="Effect allele", 
                        `type`="text", 
                        `visible`=FALSE),
                    list(
                        `name`="status", 
                        `title`="Status", 
                        `type`="text")),
                notes=list(
                    `note`="Alleles are (allele 1 / allele 2) as recorded in the source file; the genotype counts follow that order. MAF is the frequency of whichever allele is rarer.\n")))
            self$add(jmvcore::Table$new(
                options=options,
                name="openNewState",
                title="",
                visible=FALSE,
                rows=0,
                columns=list(
                    list(
                        `name`="fired", 
                        `title`="", 
                        `type`="text"))))}))

snpImportBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpImportBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SNPstats",
                name = "snpImport",
                version = c(1,1,0),
                options = options,
                results = snpImportResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Import genotypes
#'
#' Imports genotypes from PLINK (.bed/.bim/.fam, .ped/.map, .tped/.tfam) and 
#' VCF (.vcf, .vcf.gz) files for a selected list of SNPs, and opens the result 
#' -- samples, covariates and genotypes -- as a new dataset in a new jamovi 
#' window, ready for SNP Analysis and Polygenic Score.
#' 
#'
#' @examples
#' \donttest{
#' # The genotype data travels as content, not as a path: the browse
#' # button reads the selected variants in the browser and embeds only
#' # those bytes. There is deliberately no file-path option.
#'}
#' @param data .
#' @param sourceFormat Which format the carriers below hold: 'bed', 'ped',
#'   'tped' or 'vcf'. Set by the browse button from the chosen files'
#'   extensions.
#' @param genoContent Base64 of the selected genotypes, gzipped when it helps:
#'   the .bed variant blocks in the order of variantContent, or the matched
#'   .tped / VCF lines. Compression is detected by magic bytes rather than by a
#'   flag.
#' @param variantContent Base64 of the matched .bim lines, in the same order
#'   as genoContent. Empty for .tped and VCF, whose lines carry their own
#'   variant fields.
#' @param sampleContent Base64 of the whole .fam or .tfam -- sample count,
#'   order and IDs. Empty for VCF, which names its samples in the #CHROM header.
#' @param sourceDims 'bedBytes,bimLines,famLines' as the browser measured
#'   them, for the .bed path only. R re-checks that the three agree, which is
#'   the one thing the payload itself cannot reveal: the byte offset of a
#'   variant is computed from the .fam's sample count and the .bim's line
#'   number, and the length check in bed_decode_slices re-derives its
#'   expectation from those same two numbers, so a stale .fam agrees with itself
#'   and decodes the wrong variant's bytes. Empty for a payload written before
#'   this check existed, which is reported rather than refused.
#' @param genoFilename Display name of the loaded .bed/.bim/.fam trio.
#' @param loadStatus What the Load button did, or why it could not. Display
#'   only -- picking files stores the handles, and nothing is read until Load is
#'   pressed, which is what lets the files be chosen before the SNP list.
#' @param loadProblem Empty when the last Load worked or has yet to be
#'   pressed; 'error' or 'warn' when it refused, which is what makes R restate
#'   loadStatus in the results panel. The browser classifies it rather than R
#'   reading the message, because the status line is written in a dozen places
#'   and matching its wording in R would be a contract nobody can see. Needed
#'   because a refusal leaves the carriers empty and so is otherwise
#'   indistinguishable from never having loaded.
#' @param snpListText Variant IDs, one per line or whitespace-separated. Used
#'   when no selection file is loaded. Leaving both empty imports every variant
#'   in the .bim, which is only practical for a small file -- the transfer limit
#'   still applies.
#' @param snpListContent Base64 of a selection file: either one variant ID per
#'   line, or a PGS-Catalog weights file. A weights file additionally supplies
#'   the effect allele, which enables the orientation check.
#' @param snpListFilename Display name of the loaded selection file.
#' @param covContent Base64 of a delimited covariate file. Matched onto the
#'   genotype samples by ID; the genotype order is authoritative, so covariate
#'   rows that match nothing are dropped and genotype samples with no covariate
#'   row keep NA.
#' @param covFilename Display name of the loaded covariate file.
#' @param covIdCol Name of the identifier column in the covariate file. Empty
#'   detects it: IID first (the PLINK convention), then id / sample / subject,
#'   and failing all of those the first column. FID is used as well when the
#'   .fam's IIDs are not unique.
#' @param emitSamples Emits the .fam's within-family ID (IID), plus sex and
#'   phenotype when they are not missing. The family ID (FID) is added as its
#'   own column when it carries information -- that is, when the FIDs are not
#'   all identical.
#' @param dosage Numeric allele-2 dosage (0/1/2) instead of genotype factors.
#'   Costs eight times as much to transfer, so it reduces the SNP limit by
#'   roughly a factor of eight; genotype factors are what SNP Analysis expects.
#' @param filterSamples Applied before the SNP filters, as PLINK does, so the
#'   per-SNP statistics describe the samples that were kept.
#' @param maxIndMissing PLINK's --mind. Computed over the selected SNPs only,
#'   so it will not agree with a PLINK run over a whole panel.
#' @param hetSd Drop samples whose heterozygosity rate is more than this many
#'   standard deviations from the mean. 0 disables it. Heterozygosity is a
#'   contamination and inbreeding signal, but over a few hundred SNPs it is
#'   noisy -- the import report says so when the selection is small.
#' @param applyFilters Drop SNPs failing the thresholds below. Applied after
#'   reading, so the summary table shows every requested SNP with its reason for
#'   being dropped.
#' @param maxMissing PLINK's --geno. Drops SNPs missing in more than this
#'   share of samples.
#' @param minMaf PLINK's --maf. Drops SNPs below this minor allele frequency.
#' @param hweGroup Which samples the Hardy-Weinberg exact test uses. Departure
#'   from equilibrium in cases can reflect association rather than a genotyping
#'   problem, so the convention -- and PLINK's --hwe default for case/control
#'   phenotypes -- is to test controls only. Falls back to all samples when the
#'   .fam carries no phenotype. Every other statistic in the summary always
#'   describes all samples.
#' @param hweP PLINK's --hwe. Drops SNPs whose exact HWE test falls below
#'   this.
#' @param showSummary One row per imported SNP: position, alleles, N,
#'   missingness, frequency, genotype counts and the HWE exact test. Off by
#'   default because it is one row per SNP and an import can be thousands.
#' @param showProvenance What was read and what happened to it: the files, how
#'   many samples and SNPs arrived, what was not found, what the filters
#'   removed, and how the covariates matched. This is the only place several of
#'   those are stated, so it is on by default.
#' @param openNew Loads the samples, covariates and genotypes described above
#'   and opens them as a new dataset in a new jamovi window (or the current one,
#'   if it is still blank). Continue the analysis there -- this panel does not
#'   write into the sheet it runs in.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$instructions} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$notice} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$provenance} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$summary} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$openNewState} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$provenance$asDF}
#'
#' \code{as.data.frame(results$provenance)}
#'
#' @export
snpImport <- function(
    data,
    sourceFormat = "bed",
    genoContent = "",
    variantContent = "",
    sampleContent = "",
    sourceDims = "",
    genoFilename = "",
    loadStatus = "",
    loadProblem = "",
    snpListText = "",
    snpListContent = "",
    snpListFilename = "",
    covContent = "",
    covFilename = "",
    covIdCol = "",
    emitSamples = TRUE,
    dosage = FALSE,
    filterSamples = FALSE,
    maxIndMissing = 10,
    hetSd = 0,
    applyFilters = FALSE,
    maxMissing = 10,
    minMaf = 0.01,
    hweGroup = "controls",
    hweP = 0.001,
    showSummary = FALSE,
    showProvenance = TRUE,
    openNew = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("snpImport requires jmvcore to be installed (restart may be required)")

    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame())


    options <- snpImportOptions$new(
        sourceFormat = sourceFormat,
        genoContent = genoContent,
        variantContent = variantContent,
        sampleContent = sampleContent,
        sourceDims = sourceDims,
        genoFilename = genoFilename,
        loadStatus = loadStatus,
        loadProblem = loadProblem,
        snpListText = snpListText,
        snpListContent = snpListContent,
        snpListFilename = snpListFilename,
        covContent = covContent,
        covFilename = covFilename,
        covIdCol = covIdCol,
        emitSamples = emitSamples,
        dosage = dosage,
        filterSamples = filterSamples,
        maxIndMissing = maxIndMissing,
        hetSd = hetSd,
        applyFilters = applyFilters,
        maxMissing = maxMissing,
        minMaf = minMaf,
        hweGroup = hweGroup,
        hweP = hweP,
        showSummary = showSummary,
        showProvenance = showProvenance,
        openNew = openNew)

    analysis <- snpImportClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

