
# This file is automatically generated, you probably don't want to edit this

snpPGSOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpPGSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            snpCols = NULL,
            responseCol = NULL,
            covCols = NULL,
            weightingMode = "both",
            weightsPath = "",
            missingStrategy = "SNP-wise",
            normalize = TRUE,
            standardize = FALSE,
            showCoverage = TRUE,
            showDistPlot = FALSE,
            showPercentiles = FALSE,
            percentileBreaks = "20,40,60,80,90,95",
            pgsRefCategory = "middle",
            showAssoc = FALSE,
            filterValidSnps = FALSE,
            showInteraction = FALSE, ...) {

            super$initialize(
                package="SNPstats",
                name="snpPGS",
                requiresData=TRUE,
                ...)

            private$..snpCols <- jmvcore::OptionVariables$new(
                "snpCols",
                snpCols,
                suggested=list(
                    "continuous",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..responseCol <- jmvcore::OptionVariable$new(
                "responseCol",
                responseCol,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..covCols <- jmvcore::OptionVariables$new(
                "covCols",
                covCols,
                suggested=list(
                    "continuous",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..weightingMode <- jmvcore::OptionList$new(
                "weightingMode",
                weightingMode,
                options=list(
                    "weighted",
                    "unweighted",
                    "both"),
                default="both")
            private$..weightsPath <- jmvcore::OptionString$new(
                "weightsPath",
                weightsPath,
                default="")
            private$..missingStrategy <- jmvcore::OptionList$new(
                "missingStrategy",
                missingStrategy,
                options=list(
                    "SNP-wise",
                    "zero",
                    "mean",
                    "exclude"),
                default="SNP-wise")
            private$..normalize <- jmvcore::OptionBool$new(
                "normalize",
                normalize,
                default=TRUE)
            private$..standardize <- jmvcore::OptionBool$new(
                "standardize",
                standardize,
                default=FALSE)
            private$..showCoverage <- jmvcore::OptionBool$new(
                "showCoverage",
                showCoverage,
                default=TRUE)
            private$..showDistPlot <- jmvcore::OptionBool$new(
                "showDistPlot",
                showDistPlot,
                default=FALSE)
            private$..showPercentiles <- jmvcore::OptionBool$new(
                "showPercentiles",
                showPercentiles,
                default=FALSE)
            private$..percentileBreaks <- jmvcore::OptionString$new(
                "percentileBreaks",
                percentileBreaks,
                default="20,40,60,80,90,95")
            private$..pgsRefCategory <- jmvcore::OptionList$new(
                "pgsRefCategory",
                pgsRefCategory,
                options=list(
                    "lowest",
                    "middle",
                    "highest"),
                default="middle")
            private$..showAssoc <- jmvcore::OptionBool$new(
                "showAssoc",
                showAssoc,
                default=FALSE)
            private$..filterValidSnps <- jmvcore::OptionBool$new(
                "filterValidSnps",
                filterValidSnps,
                default=FALSE)
            private$..showInteraction <- jmvcore::OptionBool$new(
                "showInteraction",
                showInteraction,
                default=FALSE)
            private$..saveScores <- jmvcore::OptionOutput$new(
                "saveScores")

            self$.addOption(private$..snpCols)
            self$.addOption(private$..responseCol)
            self$.addOption(private$..covCols)
            self$.addOption(private$..weightingMode)
            self$.addOption(private$..weightsPath)
            self$.addOption(private$..missingStrategy)
            self$.addOption(private$..normalize)
            self$.addOption(private$..standardize)
            self$.addOption(private$..showCoverage)
            self$.addOption(private$..showDistPlot)
            self$.addOption(private$..showPercentiles)
            self$.addOption(private$..percentileBreaks)
            self$.addOption(private$..pgsRefCategory)
            self$.addOption(private$..showAssoc)
            self$.addOption(private$..filterValidSnps)
            self$.addOption(private$..showInteraction)
            self$.addOption(private$..saveScores)
        }),
    active = list(
        snpCols = function() private$..snpCols$value,
        responseCol = function() private$..responseCol$value,
        covCols = function() private$..covCols$value,
        weightingMode = function() private$..weightingMode$value,
        weightsPath = function() private$..weightsPath$value,
        missingStrategy = function() private$..missingStrategy$value,
        normalize = function() private$..normalize$value,
        standardize = function() private$..standardize$value,
        showCoverage = function() private$..showCoverage$value,
        showDistPlot = function() private$..showDistPlot$value,
        showPercentiles = function() private$..showPercentiles$value,
        percentileBreaks = function() private$..percentileBreaks$value,
        pgsRefCategory = function() private$..pgsRefCategory$value,
        showAssoc = function() private$..showAssoc$value,
        filterValidSnps = function() private$..filterValidSnps$value,
        showInteraction = function() private$..showInteraction$value,
        saveScores = function() private$..saveScores$value),
    private = list(
        ..snpCols = NA,
        ..responseCol = NA,
        ..covCols = NA,
        ..weightingMode = NA,
        ..weightsPath = NA,
        ..missingStrategy = NA,
        ..normalize = NA,
        ..standardize = NA,
        ..showCoverage = NA,
        ..showDistPlot = NA,
        ..showPercentiles = NA,
        ..percentileBreaks = NA,
        ..pgsRefCategory = NA,
        ..showAssoc = NA,
        ..filterValidSnps = NA,
        ..showInteraction = NA,
        ..saveScores = NA)
)

snpPGSResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpPGSResults",
    inherit = jmvcore::Group,
    active = list(
        validationMsg = function() private$.items[["validationMsg"]],
        snpGridTable = function() private$.items[["snpGridTable"]],
        coverageTable = function() private$.items[["coverageTable"]],
        summaryTable = function() private$.items[["summaryTable"]],
        saveScores = function() private$.items[["saveScores"]],
        percentileThreshTable = function() private$.items[["percentileThreshTable"]],
        percentileTable = function() private$.items[["percentileTable"]],
        assocTable = function() private$.items[["assocTable"]],
        interactionTable = function() private$.items[["interactionTable"]],
        distPlot = function() private$.items[["distPlot"]],
        stratPlot = function() private$.items[["stratPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Polygenic Score (PGS)",
                refs="SNPstats")
            self$add(jmvcore::Html$new(
                options=options,
                name="validationMsg",
                title="",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="snpGridTable",
                title="SNP Weights Used for Scoring",
                visible="(showCoverage)",
                clearWith=list(
                    "snpCols",
                    "weightsPath",
                    "weightingMode"),
                columns=list(
                    list(
                        `name`="rsid", 
                        `title`="SNP", 
                        `type`="text"),
                    list(
                        `name`="chr", 
                        `title`="Chr", 
                        `type`="text", 
                        `format`="narrow"),
                    list(
                        `name`="pos", 
                        `title`="Position", 
                        `type`="text"),
                    list(
                        `name`="effect_allele", 
                        `title`="Effect allele", 
                        `type`="text", 
                        `format`="narrow"),
                    list(
                        `name`="other_allele", 
                        `title`="Other allele", 
                        `type`="text", 
                        `format`="narrow"),
                    list(
                        `name`="effect_weight", 
                        `title`="Weight", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="matched", 
                        `title`="In dataset", 
                        `type`="text"),
                    list(
                        `name`="allele_status", 
                        `title`="Allele QC", 
                        `type`="text"),
                    list(
                        `name`="n_missing", 
                        `title`="N missing", 
                        `type`="integer"),
                    list(
                        `name`="pct_missing", 
                        `title`="% missing", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="effect_af", 
                        `title`="Effect AF", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="hwe_p", 
                        `title`="HWE p", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="extra_cols", 
                        `title`="Extra fields", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="coverageTable",
                title="SNP Coverage Summary",
                visible="(showCoverage)",
                clearWith=list(
                    "snpCols",
                    "weightsPath",
                    "weightingMode"),
                columns=list(
                    list(
                        `name`="field", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTable",
                title="PGS Summary Statistics",
                clearWith=list(
                    "snpCols",
                    "weightsPath",
                    "weightingMode",
                    "missingStrategy",
                    "normalize",
                    "standardize",
                    "responseCol",
                    "covCols"),
                columns=list(
                    list(
                        `name`="score_type", 
                        `title`="Score type", 
                        `type`="text"),
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_low", 
                        `title`="95% CI low", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_high", 
                        `title`="95% CI high", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="min", 
                        `title`="Min", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="max", 
                        `title`="Max", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="skew", 
                        `title`="Skewness", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Output$new(
                options=options,
                name="saveScores",
                title="PGS Scores",
                initInRun=TRUE,
                clearWith=list(
                    "snpCols",
                    "weightsPath",
                    "weightingMode",
                    "missingStrategy",
                    "normalize",
                    "standardize")))
            self$add(jmvcore::Table$new(
                options=options,
                name="percentileThreshTable",
                title="PGS Percentile Category Counts",
                visible="(showPercentiles)",
                clearWith=list(
                    "snpCols",
                    "weightsPath",
                    "weightingMode",
                    "missingStrategy",
                    "normalize",
                    "standardize",
                    "percentileBreaks",
                    "responseCol"),
                columns=list(
                    list(
                        `name`="score_type", 
                        `title`="Score type", 
                        `type`="text"),
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="score_range", 
                        `title`="Score range", 
                        `type`="text"),
                    list(
                        `name`="n_overall", 
                        `title`="N (%)", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="percentileTable",
                title="PGS Percentile Category Analysis",
                visible="(showPercentiles)",
                clearWith=list(
                    "snpCols",
                    "weightsPath",
                    "weightingMode",
                    "missingStrategy",
                    "normalize",
                    "standardize",
                    "responseCol",
                    "covCols",
                    "percentileBreaks",
                    "pgsRefCategory"),
                columns=list(
                    list(
                        `name`="score_type", 
                        `title`="Score type", 
                        `type`="text"),
                    list(
                        `name`="category", 
                        `title`="Category", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="score_range", 
                        `title`="Score range", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_low", 
                        `title`="95% CI low", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_high", 
                        `title`="95% CI high", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue")),
                notes=list(
                    `modelNote`="", 
                    `refNote`="", 
                    `covNote`="")))
            self$add(jmvcore::Table$new(
                options=options,
                name="assocTable",
                title="PGS\u2013Response Association",
                visible="(showAssoc)",
                clearWith=list(
                    "snpCols",
                    "weightsPath",
                    "weightingMode",
                    "missingStrategy",
                    "normalize",
                    "standardize",
                    "responseCol",
                    "covCols"),
                columns=list(
                    list(
                        `name`="score_type", 
                        `title`="Score type", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="stat_label", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_low", 
                        `title`="95% CI low", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_high", 
                        `title`="95% CI high", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="stat", 
                        `title`="Value", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`=FALSE),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="text", 
                        `visible`=FALSE),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`=FALSE),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue")),
                notes=list(
                    `covNote`="", 
                    `respNote`="")))
            self$add(jmvcore::Table$new(
                options=options,
                name="interactionTable",
                title="PGS \u00D7 Covariate Interaction",
                visible="(showInteraction)",
                clearWith=list(
                    "snpCols",
                    "weightsPath",
                    "weightingMode",
                    "missingStrategy",
                    "normalize",
                    "standardize",
                    "responseCol",
                    "covCols"),
                columns=list(
                    list(
                        `name`="score_type", 
                        `title`="Score type", 
                        `type`="text"),
                    list(
                        `name`="model", 
                        `title`="Model", 
                        `type`="text"),
                    list(
                        `name`="term", 
                        `title`="Term", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_low", 
                        `title`="95% CI low", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_high", 
                        `title`="95% CI high", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue")),
                notes=list(
                    `intNote`="")))
            self$add(jmvcore::Image$new(
                options=options,
                name="distPlot",
                title="Score Distribution",
                visible="(showDistPlot)",
                width=560,
                height=390,
                renderFun=".plotDist"))
            self$add(jmvcore::Image$new(
                options=options,
                name="stratPlot",
                title="PGS by Group",
                visible=FALSE,
                width=560,
                height=420,
                renderFun=".plotStrat"))}))

snpPGSBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpPGSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SNPstats",
                name = "snpPGS",
                version = c(0,1,0),
                options = options,
                results = snpPGSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'none')
        }))

#' Polygenic Score (PGS)
#'
#' 
#' @param data [object Object]
#' @param snpCols One column per SNP. Dosage (0/1/2) or allele strings
#'   auto-detected per column.
#' @param responseCol Optional outcome variable. If provided, an association
#'   test between PGS and response is reported (logistic for binary, linear for
#'   continuous).
#' @param covCols Optional covariate columns. If provided, regression models
#'   (logistic and linear) are adjusted for these variables. A note listing the
#'   covariates is added to the association table.
#' @param weightingMode Controls how SNP weights are applied. 'weighted' uses
#'   effect_weight values from the loaded PGS Catalog file. 'unweighted' assigns
#'   weight 1 to every SNP regardless of the file. 'both' computes and reports
#'   both scores side by side in the summary and association tables. If no
#'   weights file is loaded, unweighted scoring is used automatically.
#' @param weightsPath Path to a PGS Catalog-format file. Lines starting with
#'   '#' are skipped automatically. Recognised columns: rsID/variant_id,
#'   effect_allele, other_allele, effect_weight/beta, chr_name/chr,
#'   chr_position/pos. Missing expected columns are hidden in output; extra
#'   columns are shown concatenated in an 'Extra fields' column.
#' @param missingStrategy Strategy for handling missing genotype values.
#'   'SNP-wise' scores each individual using only their observed SNPs and
#'   divides by that individual's observed SNP count, keeping all individuals
#'   regardless of missingness.
#' @param normalize If TRUE, divides each individual's raw score by the
#'   maximum score they could have achieved given their observed SNPs. For
#'   unweighted scoring: max = 2 × observed SNP count. For weighted scoring:
#'   max = 2 × sum of weights for observed SNPs. Individuals with missing SNPs
#'   get a per-individual maximum, so scores remain comparable across
#'   individuals with different missingness. Result is in [0, 1].
#' @param standardize If TRUE, divides the (optionally normalized) PGS by its
#'   standard deviation across all individuals. The resulting score has SD = 1,
#'   so regression coefficients represent the effect per 1-SD change in PGS.
#' @param showCoverage Show the SNP coverage summary table.
#' @param showDistPlot Show the score distribution histogram and density plot.
#' @param showPercentiles Show percentile ranks for each individual and
#'   threshold table.
#' @param percentileBreaks Comma-separated list of percentile thresholds used
#'   to partition individuals into categories (e.g. "20,40,60,80" creates five
#'   bands: <P20, P20–P40, P40–P60, P60–P80, >P80).
#' @param pgsRefCategory The percentile category used as the reference group
#'   in logistic (binary response) or linear (continuous response) regression.
#'   'lowest' uses the bottom band (<lowest threshold), 'highest' uses the top
#'   band (>highest threshold), and 'middle' uses the band containing the median
#'   of the score distribution.
#' @param showAssoc Show the PGS-response association table (requires a
#'   response variable to be selected).
#' @param filterValidSnps If TRUE, the SNP Weights table is filtered to show
#'   only SNPs that passed QC and were used in scoring. SNPs excluded due to
#'   allele mismatch, missing data, or being monomorphic are hidden.
#' @param showInteraction If TRUE, fits an interaction model between the PGS
#'   and the first selected covariate (pgs × cov1) and reports the interaction
#'   term in a dedicated table. Requires both a response variable and at least
#'   one covariate. For binary responses a logistic model is used; for
#'   continuous responses a linear model is used.
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$validationMsg} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$snpGridTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$coverageTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$summaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$saveScores} \tab \tab \tab \tab \tab an output \cr
#'   \code{results$percentileThreshTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$percentileTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$assocTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$interactionTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$distPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$stratPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$snpGridTable$asDF}
#'
#' \code{as.data.frame(results$snpGridTable)}
#'
#' @export
snpPGS <- function(
    data,
    snpCols,
    responseCol,
    covCols,
    weightingMode = "both",
    weightsPath = "",
    missingStrategy = "SNP-wise",
    normalize = TRUE,
    standardize = FALSE,
    showCoverage = TRUE,
    showDistPlot = FALSE,
    showPercentiles = FALSE,
    percentileBreaks = "20,40,60,80,90,95",
    pgsRefCategory = "middle",
    showAssoc = FALSE,
    filterValidSnps = FALSE,
    showInteraction = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("snpPGS requires jmvcore to be installed (restart may be required)")

    if ( ! missing(snpCols)) snpCols <- jmvcore::resolveQuo(jmvcore::enquo(snpCols))
    if ( ! missing(responseCol)) responseCol <- jmvcore::resolveQuo(jmvcore::enquo(responseCol))
    if ( ! missing(covCols)) covCols <- jmvcore::resolveQuo(jmvcore::enquo(covCols))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(snpCols), snpCols, NULL),
            `if`( ! missing(responseCol), responseCol, NULL),
            `if`( ! missing(covCols), covCols, NULL))


    options <- snpPGSOptions$new(
        snpCols = snpCols,
        responseCol = responseCol,
        covCols = covCols,
        weightingMode = weightingMode,
        weightsPath = weightsPath,
        missingStrategy = missingStrategy,
        normalize = normalize,
        standardize = standardize,
        showCoverage = showCoverage,
        showDistPlot = showDistPlot,
        showPercentiles = showPercentiles,
        percentileBreaks = percentileBreaks,
        pgsRefCategory = pgsRefCategory,
        showAssoc = showAssoc,
        filterValidSnps = filterValidSnps,
        showInteraction = showInteraction)

    analysis <- snpPGSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

