
# This file is automatically generated, you probably don't want to edit this

snpPGSOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpPGSOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            idCol = NULL,
            snpCols = NULL,
            responseCol = NULL,
            weightsPath = "",
            weightingMode = "weighted",
            missingStrategy = "mean",
            normalize = TRUE,
            standardize = FALSE,
            showCoverage = TRUE,
            showScoreTable = FALSE,
            showDistPlot = FALSE,
            showPercentiles = FALSE,
            percentileBreaks = "20,40,60,80,90,95",
            showAssoc = FALSE, ...) {

            super$initialize(
                package="SNPstats",
                name="snpPGS",
                requiresData=TRUE,
                ...)

            private$..idCol <- jmvcore::OptionVariable$new(
                "idCol",
                idCol,
                suggested=list(
                    "nominal",
                    "id"),
                permitted=list(
                    "factor",
                    "numeric",
                    "id"))
            private$..snpCols <- jmvcore::OptionVariables$new(
                "snpCols",
                snpCols,
                suggested=list(
                    "continuous",
                    "nominal"),
                permitted=list(
                    "numeric",
                    "factor"))
            private$..responseCol <- jmvcore::OptionVariable$new(
                "responseCol",
                responseCol,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"))
            private$..weightsPath <- jmvcore::OptionString$new(
                "weightsPath",
                weightsPath,
                default="")
            private$..weightingMode <- jmvcore::OptionList$new(
                "weightingMode",
                weightingMode,
                options=list(
                    "weighted",
                    "unweighted",
                    "both"),
                default="weighted")
            private$..missingStrategy <- jmvcore::OptionList$new(
                "missingStrategy",
                missingStrategy,
                options=list(
                    "mean",
                    "zero",
                    "exclude",
                    "snp_wise"),
                default="mean")
            private$..normalize <- jmvcore::OptionBool$new(
                "normalize",
                normalize,
                default=TRUE)
            private$..standardize <- jmvcore::OptionBool$new(
                "standardize",
                standardize,
                default=FALSE)
            private$..showCoverage <- jmvcore::OptionBool$new(
                "showCoverage",
                showCoverage,
                default=TRUE)
            private$..showScoreTable <- jmvcore::OptionBool$new(
                "showScoreTable",
                showScoreTable,
                default=FALSE)
            private$..showDistPlot <- jmvcore::OptionBool$new(
                "showDistPlot",
                showDistPlot,
                default=FALSE)
            private$..showPercentiles <- jmvcore::OptionBool$new(
                "showPercentiles",
                showPercentiles,
                default=FALSE)
            private$..percentileBreaks <- jmvcore::OptionString$new(
                "percentileBreaks",
                percentileBreaks,
                default="20,40,60,80,90,95")
            private$..showAssoc <- jmvcore::OptionBool$new(
                "showAssoc",
                showAssoc,
                default=FALSE)

            self$.addOption(private$..idCol)
            self$.addOption(private$..snpCols)
            self$.addOption(private$..responseCol)
            self$.addOption(private$..weightsPath)
            self$.addOption(private$..weightingMode)
            self$.addOption(private$..missingStrategy)
            self$.addOption(private$..normalize)
            self$.addOption(private$..standardize)
            self$.addOption(private$..showCoverage)
            self$.addOption(private$..showScoreTable)
            self$.addOption(private$..showDistPlot)
            self$.addOption(private$..showPercentiles)
            self$.addOption(private$..percentileBreaks)
            self$.addOption(private$..showAssoc)
        }),
    active = list(
        idCol = function() private$..idCol$value,
        snpCols = function() private$..snpCols$value,
        responseCol = function() private$..responseCol$value,
        weightsPath = function() private$..weightsPath$value,
        weightingMode = function() private$..weightingMode$value,
        missingStrategy = function() private$..missingStrategy$value,
        normalize = function() private$..normalize$value,
        standardize = function() private$..standardize$value,
        showCoverage = function() private$..showCoverage$value,
        showScoreTable = function() private$..showScoreTable$value,
        showDistPlot = function() private$..showDistPlot$value,
        showPercentiles = function() private$..showPercentiles$value,
        percentileBreaks = function() private$..percentileBreaks$value,
        showAssoc = function() private$..showAssoc$value),
    private = list(
        ..idCol = NA,
        ..snpCols = NA,
        ..responseCol = NA,
        ..weightsPath = NA,
        ..weightingMode = NA,
        ..missingStrategy = NA,
        ..normalize = NA,
        ..standardize = NA,
        ..showCoverage = NA,
        ..showScoreTable = NA,
        ..showDistPlot = NA,
        ..showPercentiles = NA,
        ..percentileBreaks = NA,
        ..showAssoc = NA)
)

snpPGSResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpPGSResults",
    inherit = jmvcore::Group,
    active = list(
        validationMsg = function() private$.items[["validationMsg"]],
        snpGridTable = function() private$.items[["snpGridTable"]],
        coverageTable = function() private$.items[["coverageTable"]],
        summaryTable = function() private$.items[["summaryTable"]],
        scoreTable = function() private$.items[["scoreTable"]],
        percentileTable = function() private$.items[["percentileTable"]],
        assocTable = function() private$.items[["assocTable"]],
        distPlot = function() private$.items[["distPlot"]],
        stratPlot = function() private$.items[["stratPlot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Polygenic Score (PGS)",
                refs="SNPstats")
            self$add(jmvcore::Html$new(
                options=options,
                name="validationMsg",
                title="",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="snpGridTable",
                title="SNP Weights Used for Scoring",
                visible="(showCoverage)",
                clearWith=list(
                    "snpCols",
                    "weightsPath",
                    "weightingMode"),
                columns=list(
                    list(
                        `name`="rsid", 
                        `title`="SNP (rsID / column)", 
                        `type`="text"),
                    list(
                        `name`="chr", 
                        `title`="Chr", 
                        `type`="text"),
                    list(
                        `name`="pos", 
                        `title`="Position", 
                        `type`="text"),
                    list(
                        `name`="effect_allele", 
                        `title`="Effect allele", 
                        `type`="text"),
                    list(
                        `name`="other_allele", 
                        `title`="Other allele", 
                        `type`="text"),
                    list(
                        `name`="effect_weight", 
                        `title`="Weight", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="matched", 
                        `title`="In dataset", 
                        `type`="text"),
                    list(
                        `name`="allele_status", 
                        `title`="Allele QC", 
                        `type`="text"),
                    list(
                        `name`="n_missing", 
                        `title`="N missing", 
                        `type`="integer"),
                    list(
                        `name`="pct_missing", 
                        `title`="% missing", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="extra_cols", 
                        `title`="Extra fields", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="coverageTable",
                title="SNP Coverage Summary",
                visible="(showCoverage)",
                clearWith=list(
                    "snpCols",
                    "weightsPath",
                    "weightingMode"),
                columns=list(
                    list(
                        `name`="field", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="summaryTable",
                title="PGS Summary Statistics",
                clearWith=list(
                    "snpCols",
                    "weightsPath",
                    "weightingMode",
                    "missingStrategy",
                    "normalize",
                    "standardize",
                    "responseCol"),
                columns=list(
                    list(
                        `name`="score_type", 
                        `title`="Score type", 
                        `type`="text"),
                    list(
                        `name`="group", 
                        `title`="Group", 
                        `type`="text"),
                    list(
                        `name`="n", 
                        `title`="N", 
                        `type`="integer"),
                    list(
                        `name`="mean", 
                        `title`="Mean", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="sd", 
                        `title`="SD", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_low", 
                        `title`="95% CI low", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_high", 
                        `title`="95% CI high", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="min", 
                        `title`="Min", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="max", 
                        `title`="Max", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="skew", 
                        `title`="Skewness", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="scoreTable",
                title="Per-Individual Scores",
                visible="(showScoreTable)",
                clearWith=list(
                    "snpCols",
                    "weightsPath",
                    "weightingMode",
                    "missingStrategy",
                    "normalize",
                    "standardize"),
                columns=list(
                    list(
                        `name`="individual", 
                        `title`="Individual", 
                        `type`="text"),
                    list(
                        `name`="pgs", 
                        `title`="PGS Score", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="pgs_z", 
                        `title`="Z-score", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="percentile", 
                        `title`="Percentile", 
                        `type`="number", 
                        `format`="zto", 
                        `visible`="(showPercentiles)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="percentileTable",
                title="Percentile Thresholds",
                visible="(showPercentiles)",
                clearWith=list(
                    "snpCols",
                    "weightsPath",
                    "weightingMode",
                    "missingStrategy",
                    "normalize",
                    "standardize",
                    "percentileBreaks"),
                columns=list(
                    list(
                        `name`="threshold", 
                        `title`="Percentile", 
                        `type`="text"),
                    list(
                        `name`="score", 
                        `title`="PGS Score", 
                        `type`="number", 
                        `format`="zto"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="assocTable",
                title="PGS\u2013Response Association",
                visible="(showAssoc)",
                clearWith=list(
                    "snpCols",
                    "weightsPath",
                    "weightingMode",
                    "missingStrategy",
                    "normalize",
                    "standardize",
                    "responseCol"),
                columns=list(
                    list(
                        `name`="score_type", 
                        `title`="Score type", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="Test", 
                        `type`="text"),
                    list(
                        `name`="stat_label", 
                        `title`="Statistic", 
                        `type`="text"),
                    list(
                        `name`="estimate", 
                        `title`="Estimate", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_low", 
                        `title`="95% CI low", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="ci_high", 
                        `title`="95% CI high", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="stat", 
                        `title`="Value", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="df", 
                        `title`="df", 
                        `type`="text"),
                    list(
                        `name`="p", 
                        `title`="p-value", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="distPlot",
                title="Score Distribution",
                visible="(showDistPlot)",
                width=560,
                height=390,
                renderFun=".plotDist"))
            self$add(jmvcore::Image$new(
                options=options,
                name="stratPlot",
                title="PGS by Group",
                visible=FALSE,
                width=560,
                height=420,
                renderFun=".plotStrat"))}))

snpPGSBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpPGSBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SNPstats",
                name = "snpPGS",
                version = c(0,5,0),
                options = options,
                results = snpPGSResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Polygenic Score (PGS)
#'
#' 
#' @param data [object Object]
#' @param idCol Column identifying each individual. Row numbers used if
#'   omitted.
#' @param snpCols One column per SNP. Dosage (0/1/2) or allele strings
#'   auto-detected per column.
#' @param responseCol Optional outcome variable. If provided, an association
#'   test between PGS and response is reported (logistic for binary, linear for
#'   continuous).
#' @param weightsPath Path to a PGS Catalog-format file. Lines starting with
#'   '#' are skipped automatically. Recognised columns: rsID/variant_id,
#'   effect_allele, other_allele, effect_weight/beta, chr_name/chr,
#'   chr_position/pos. Missing expected columns are hidden in output; extra
#'   columns are shown concatenated in an 'Extra fields' column.
#' @param weightingMode Controls how SNP weights are applied. 'weighted' uses
#'   effect_weight values from the loaded PGS Catalog file. 'unweighted' assigns
#'   weight 1 to every SNP regardless of the file. 'both' computes and reports
#'   both scores side by side in the summary and association tables. If no
#'   weights file is loaded, unweighted scoring is used automatically.
#' @param missingStrategy Strategy for handling missing genotype values.
#'   'snp_wise' scores each individual using only their observed SNPs and
#'   divides by that individual's observed SNP count, keeping all individuals
#'   regardless of missingness.
#' @param normalize If TRUE, divides each individual's PGS by the number of
#'   SNPs that were actually observed (non-missing) for that individual. This
#'   corrects for differential missingness: individuals with fewer observed SNPs
#'   are not systematically penalised.
#' @param standardize If TRUE, divides the (optionally normalized) PGS by its
#'   standard deviation across all individuals. The resulting score has SD = 1,
#'   so regression coefficients represent the effect per 1-SD change in PGS.
#' @param showCoverage Show the SNP coverage summary table.
#' @param showScoreTable Show the per-individual PGS score table.
#' @param showDistPlot Show the score distribution histogram and density plot.
#' @param showPercentiles Show percentile ranks for each individual and
#'   threshold table.
#' @param percentileBreaks Comma-separated list of percentile thresholds for
#'   the threshold table.
#' @param showAssoc Show the PGS-response association table (requires a
#'   response variable to be selected).
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$validationMsg} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$snpGridTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$coverageTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$summaryTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$scoreTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$percentileTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$assocTable} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$distPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$stratPlot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$snpGridTable$asDF}
#'
#' \code{as.data.frame(results$snpGridTable)}
#'
#' @export
snpPGS <- function(
    data,
    idCol,
    snpCols,
    responseCol,
    weightsPath = "",
    weightingMode = "weighted",
    missingStrategy = "mean",
    normalize = TRUE,
    standardize = FALSE,
    showCoverage = TRUE,
    showScoreTable = FALSE,
    showDistPlot = FALSE,
    showPercentiles = FALSE,
    percentileBreaks = "20,40,60,80,90,95",
    showAssoc = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("snpPGS requires jmvcore to be installed (restart may be required)")

    if ( ! missing(idCol)) idCol <- jmvcore::resolveQuo(jmvcore::enquo(idCol))
    if ( ! missing(snpCols)) snpCols <- jmvcore::resolveQuo(jmvcore::enquo(snpCols))
    if ( ! missing(responseCol)) responseCol <- jmvcore::resolveQuo(jmvcore::enquo(responseCol))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(idCol), idCol, NULL),
            `if`( ! missing(snpCols), snpCols, NULL),
            `if`( ! missing(responseCol), responseCol, NULL))


    options <- snpPGSOptions$new(
        idCol = idCol,
        snpCols = snpCols,
        responseCol = responseCol,
        weightsPath = weightsPath,
        weightingMode = weightingMode,
        missingStrategy = missingStrategy,
        normalize = normalize,
        standardize = standardize,
        showCoverage = showCoverage,
        showScoreTable = showScoreTable,
        showDistPlot = showDistPlot,
        showPercentiles = showPercentiles,
        percentileBreaks = percentileBreaks,
        showAssoc = showAssoc)

    analysis <- snpPGSClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

