# snpPGS_b.R  — Analysis class for SNPstats PGS module
#
# Inherits from snpPGSBase (auto-generated by jmvtools from the yaml files).
#
# Key differences from v0.3:
#   • All weight / allele information is read from self$options$snpGrid
#     (the editable per-SNP grid) rather than re-parsing the file.
#     The file is only parsed as a fallback when the grid is empty.
#   • self$options$weightMode ("catalog" | "equal") controls whether
#     effect_weight from the grid is used or everything is weighted 1.
#   • Results include a snpGridTable showing exactly what was used.
# ─────────────────────────────────────────────────────────────────────────────

snpPGSClass <- R6::R6Class(
  "snpPGSClass",
  inherit = snpPGSBase,

  private = list(

    # ── Cached per-run objects (populated in .run, used in .plotDist) ────────
    .pgsScores  = NULL,   # numeric vector, one value per individual
    .idLabels   = NULL,   # character vector of individual labels

    # ════════════════════════════════════════════════════════════════════════
    # .run  — main entry point called by jamovi
    # ════════════════════════════════════════════════════════════════════════
    .run = function() {

      # ── 1. Retrieve options ──────────────────────────────────────────────
      snpCols    <- self$options$snpCols
      idCol      <- self$options$idCol
      respCol    <- self$options$responseCol
      grid       <- self$options$snpGrid       # list of lists
      weightMode <- self$options$weightMode    # "catalog" | "equal"
      missing_st <- self$options$missingStrategy
      normalize  <- self$options$normalize

      # ── 2. Basic input validation ────────────────────────────────────────
      if (is.null(snpCols) || length(snpCols) == 0) {
        self$results$validationMsg$setContent(
          "<p style='color:#c0392b;'>Please add at least one SNP column.</p>")
        self$results$validationMsg$setVisible(TRUE)
        return()
      }
      self$results$validationMsg$setVisible(FALSE)

      # ── 3. Build the effective weight table from snpGrid ─────────────────
      #
      # wtable: data.frame with columns
      #   rsid, effect_allele, other_allele, effect_weight, chr, pos, matched
      #
      # Strategy:
      #   (a) If the grid has rows, use them as the authoritative source.
      #   (b) If the grid is empty but weightsPath is set, parse the file
      #       directly (fallback for programmatic / non-UI use).
      #   (c) If neither, create a unit-weight row for every snpCol.
      # ────────────────────────────────────────────────────────────────────
      wtable <- private$.buildWeightTable(snpCols, grid)

      # ── 4. Populate snpGridTable (shows exactly what will be used) ────────
      private$.fillSnpGridTable(wtable)

      # ── 5. Build dosage matrix  ──────────────────────────────────────────
      #   Rows = individuals, columns = SNPs present in dataset
      dosage <- private$.buildDosageMatrix(snpCols, wtable, missing_st)
      if (is.null(dosage)) return()   # error already reported

      # ── 6. Compute per-individual PGS ────────────────────────────────────
      matchedRows <- wtable[wtable$rsid %in% colnames(dosage), ]
      weights_vec <- setNames(matchedRows$effect_weight, matchedRows$rsid)
      weights_vec <- weights_vec[colnames(dosage)]   # align to dosage column order

      # NA weights arise when a SNP was in snpCols but not in the catalog
      # (grid was never populated for that SNP, or file had no entry).
      # For "catalog" mode: drop those SNPs from scoring and warn.
      # For "equal" mode:   all weights become 1 anyway.
      if (weightMode == "equal") {
        weights_vec[is.na(weights_vec)] <- 1
      } else {
        na_snps <- names(weights_vec)[is.na(weights_vec)]
        if (length(na_snps) > 0) {
          self$results$validationMsg$setContent(paste0(
            "<p style='color:#e67e22;'>Warning: the following SNPs have no catalog weight ",
            "and will be excluded from scoring: ",
            paste(na_snps, collapse = ", "), ". ",
            "Load a weights file or switch to equal-weight mode.</p>"))
          self$results$validationMsg$setVisible(TRUE)
          # Drop columns with no weight
          keep_cols   <- names(weights_vec)[!is.na(weights_vec)]
          dosage      <- dosage[, keep_cols, drop = FALSE]
          weights_vec <- weights_vec[keep_cols]
        }
      }

      if (length(weights_vec) == 0) {
        self$results$validationMsg$setContent(
          "<p style='color:#c0392b;'>No SNPs with valid weights — cannot compute PGS.</p>")
        self$results$validationMsg$setVisible(TRUE)
        return()
      }

      scores <- as.numeric(dosage %*% weights_vec)

      if (normalize && length(weights_vec) > 0) {
        scores <- scores / length(weights_vec)
      }

      private$.pgsScores <- scores

      # ── 7. Individual IDs ────────────────────────────────────────────────
      if (!is.null(idCol) && idCol %in% names(self$data)) {
        private$.idLabels <- as.character(self$data[[idCol]])
      } else {
        private$.idLabels <- as.character(seq_along(scores))
      }

      # ── 8. Coverage table ─────────────────────────────────────────────────
      private$.fillCoverageTable(snpCols, wtable, missing_st, weightMode)

      # ── 9. Summary statistics ────────────────────────────────────────────
      private$.fillSummaryTable(scores)

      # ── 10. Per-individual score table ───────────────────────────────────
      if (self$options$showScoreTable || self$options$showPercentiles) {
        private$.fillScoreTable(scores, private$.idLabels)
      }

      # ── 11. Percentile threshold table ───────────────────────────────────
      if (self$options$showPercentiles) {
        private$.fillPercentileTable(scores)
      }

      # ── 12. PGS–response association ─────────────────────────────────────
      if (self$options$showAssoc && !is.null(respCol) && nchar(respCol) > 0) {
        private$.fillAssocTable(scores, respCol)
      }
    },  # end .run


    # ════════════════════════════════════════════════════════════════════════
    # .buildWeightTable
    # Returns a data.frame: rsid | effect_allele | other_allele |
    #                        effect_weight | chr | pos | matched
    # ════════════════════════════════════════════════════════════════════════
    .buildWeightTable = function(snpCols, grid) {

      if (!is.null(grid) && length(grid) > 0) {
        # ── (a) Grid populated by the UI ──────────────────────────────────
        rows <- lapply(grid, function(r) {
          # JS blankRow uses null for weight (not-yet-set sentinel).
          # R receives NULL; convert to NA so we can handle it uniformly.
          w_raw <- r$effect_weight
          w     <- if (is.null(w_raw)) NA_real_ else as.numeric(w_raw)
          # If still NA after catalog merge, fall back to 1 for equal-weight
          # mode compatibility. Catalog mode will handle NA separately.
          data.frame(
            rsid          = as.character(r$rsid),
            effect_allele = as.character(r$effect_allele %||% ""),
            other_allele  = as.character(r$other_allele  %||% ""),
            effect_weight = w,
            chr           = as.character(r$chr           %||% ""),
            pos           = as.character(r$pos           %||% ""),
            matched       = isTRUE(r$matched),
            stringsAsFactors = FALSE
          )
        })
        return(do.call(rbind, rows))
      }

      # ── (b) Fallback: parse file directly (programmatic use) ────────────
      path    <- self$options$weightsPath
      sepOpt  <- self$options$weightsSep
      if (!is.null(path) && nchar(trimws(path)) > 0 && file.exists(path)) {
        return(private$.parseCatalogFile(path, sepOpt, snpCols))
      }

      # ── (c) No grid and no file — unit weights for all selected columns ──
      data.frame(
        rsid          = snpCols,
        effect_allele = "",
        other_allele  = "",
        effect_weight = 1,
        chr           = "",
        pos           = "",
        matched       = FALSE,
        stringsAsFactors = FALSE
      )
    },


    # ════════════════════════════════════════════════════════════════════════
    # .parseCatalogFile  (fallback parser for programmatic use — mirrors JS)
    #
    # PGS Catalog v2.0 format specifics handled here:
    #   • Comment/metadata lines: start with '#', '##', or '###'
    #   • Metadata key=value lines: #pgs_id=PGS001901, #weight_type=beta, etc.
    #   • Column header is the first non-comment line (tab-delimited)
    #   • rsID column is named exactly "rsID" (capital I, capital D)
    #   • effect_weight is a float that CAN be 0 or negative (beta values)
    #     → never coerce 0 → 1 as a fallback
    # ════════════════════════════════════════════════════════════════════════
    .parseCatalogFile = function(path, sepOpt, snpCols) {
      raw <- tryCatch(readLines(path, warn = FALSE), error = function(e) NULL)
      if (is.null(raw)) {
        self$results$validationMsg$setContent(
          paste0("<p style='color:#c0392b;'>Cannot read weights file: ", path, "</p>"))
        self$results$validationMsg$setVisible(TRUE)
        return(NULL)
      }

      # ── Extract PGS metadata from '#key=value' lines ─────────────────────
      meta <- private$.parseFileMetadata(raw)

      # ── Data lines: non-empty, non-comment ───────────────────────────────
      dataLines <- raw[!grepl("^#", raw) & nchar(trimws(raw)) > 0]
      if (length(dataLines) < 2) return(private$.unitWeightTable(snpCols))

      # ── Delimiter detection ───────────────────────────────────────────────
      sep <- switch(sepOpt,
        comma = ",",
        tab   = "\t",
        {  # auto-detect: PGS Catalog is always tab, but support CSV exports
          first <- dataLines[1]
          ntabs   <- lengths(regmatches(first, gregexpr("\t", first)))
          ncommas <- lengths(regmatches(first, gregexpr(",",  first)))
          if (ntabs >= ncommas) "\t" else ","
        }
      )

      # ── Parse into data.frame ─────────────────────────────────────────────
      df <- tryCatch(
        read.table(text   = paste(dataLines, collapse = "\n"),
                   header = TRUE, sep = sep,
                   stringsAsFactors = FALSE, quote = "\"",
                   fill = TRUE, comment.char = "", check.names = FALSE),
        error = function(e) NULL
      )
      if (is.null(df) || nrow(df) == 0) return(private$.unitWeightTable(snpCols))

      # Normalise column names for lookup (keep originals for display)
      orig_names  <- names(df)
      lower_names <- tolower(orig_names)

      find_col <- function(candidates) {
        for (cn in tolower(candidates))
          if (cn %in% lower_names) return(orig_names[match(cn, lower_names)])
        NULL
      }

      # Real PGS Catalog v2.0 column names listed first
      c_rsid   <- find_col(c("rsID",        "rsid", "variant_id", "snp", "snp_id", "marker_name"))
      c_ea     <- find_col(c("effect_allele"))
      c_oa     <- find_col(c("other_allele", "ref_allele", "non_effect_allele", "reference_allele"))
      c_weight <- find_col(c("effect_weight","beta",  "weight", "or"))
      c_chr    <- find_col(c("chr_name",     "chromosome", "chr", "chrom"))
      c_pos    <- find_col(c("chr_position", "position",   "pos", "bp"))

      if (is.null(c_rsid)) {
        self$results$validationMsg$setContent(
          "<p style='color:#c0392b;'>Weights file has no recognisable rsID / variant_id column.</p>")
        self$results$validationMsg$setVisible(TRUE)
        return(private$.unitWeightTable(snpCols))
      }

      # ── Build result data.frame ───────────────────────────────────────────
      # effect_weight: use NA (not 1) when the cell is empty/unparseable,
      # so downstream code can distinguish "missing" from a real zero/beta.
      weight_raw <- if (!is.null(c_weight)) suppressWarnings(as.numeric(df[[c_weight]])) else NA_real_

      result <- data.frame(
        rsid          = as.character(df[[c_rsid]]),
        effect_allele = if (!is.null(c_ea))  as.character(df[[c_ea]])  else "",
        other_allele  = if (!is.null(c_oa))  as.character(df[[c_oa]])  else "",
        effect_weight = weight_raw,   # NA allowed here — handled in .buildDosageMatrix
        chr           = if (!is.null(c_chr)) as.character(df[[c_chr]]) else "",
        pos           = if (!is.null(c_pos)) as.character(df[[c_pos]]) else "",
        matched       = TRUE,
        stringsAsFactors = FALSE
      )

      # Attach metadata as an attribute so .fillCoverageTable can use it
      attr(result, "pgs_meta") <- meta

      result
    },

    # ── Parse '#key=value' metadata lines from raw file lines ────────────────
    .parseFileMetadata = function(raw_lines) {
      meta <- list(pgs_id = "", pgs_name = "", trait_reported = "",
                   weight_type = "", genome_build = "", variants_number = "")
      keys <- names(meta)
      for (ln in raw_lines) {
        if (!grepl("^#", ln)) break          # stop at first data line
        inner <- sub("^#+", "", ln)          # strip leading hashes
        eq    <- regexpr("=", inner)
        if (eq == -1) next
        k <- trimws(substr(inner, 1, eq - 1))
        v <- trimws(substr(inner, eq + 1, nchar(inner)))
        if (tolower(k) %in% keys) meta[[tolower(k)]] <- v
      }
      meta
    },

    .unitWeightTable = function(snpCols) {
      data.frame(rsid = snpCols, effect_allele = "", other_allele = "",
                 effect_weight = 1, chr = "", pos = "", matched = FALSE,
                 stringsAsFactors = FALSE)
    },


    # ════════════════════════════════════════════════════════════════════════
    # .buildDosageMatrix
    # Returns a numeric matrix [n_individuals × n_matched_snps] or NULL
    # ════════════════════════════════════════════════════════════════════════
    .buildDosageMatrix = function(snpCols, wtable, missing_st) {
      # Only use SNPs that are both selected AND present in the dataset
      useCols <- intersect(wtable$rsid, intersect(snpCols, names(self$data)))

      if (length(useCols) == 0) {
        self$results$validationMsg$setContent(
          "<p style='color:#c0392b;'>None of the selected SNP columns could be matched to the dataset.</p>")
        self$results$validationMsg$setVisible(TRUE)
        return(NULL)
      }

      mat <- matrix(NA_real_, nrow = nrow(self$data), ncol = length(useCols),
                    dimnames = list(NULL, useCols))

      for (snp in useCols) {
        col_raw <- self$data[[snp]]

        # ── Dosage detection ──────────────────────────────────────────────
        # Numeric columns: use directly as dosage (0/1/2 or imputed values).
        # Factor / character columns: count copies of effect_allele.
        if (is.numeric(col_raw)) {
          dosage_col <- col_raw
        } else {
          # Allele-string encoding, e.g. "AG", "AA", "GG"
          col_char <- as.character(col_raw)
          ea_row <- wtable[wtable$rsid == snp, ]
          ea <- if (nrow(ea_row) > 0 && nchar(ea_row$effect_allele[1]) > 0)
                    ea_row$effect_allele[1]
                else NA_character_

          if (is.na(ea)) {
            # No allele info — fallback: treat as missing
            dosage_col <- rep(NA_real_, length(col_char))
          } else {
            # Count occurrences of the effect allele in the genotype string
            dosage_col <- vapply(col_char, function(g) {
              if (is.na(g) || g == "") return(NA_real_)
              alleles <- strsplit(g, "")[[1]]
              sum(alleles == ea)
            }, numeric(1))
          }
        }

        # ── Missing value handling ────────────────────────────────────────
        na_mask <- is.na(dosage_col)
        if (any(na_mask)) {
          dosage_col <- switch(missing_st,
            mean    = { m <- mean(dosage_col, na.rm = TRUE); dosage_col[na_mask] <- m; dosage_col },
            zero    = { dosage_col[na_mask] <- 0; dosage_col },
            exclude = dosage_col   # handled below after matrix assembly
          )
        }
        mat[, snp] <- dosage_col
      }

      # Exclude individuals with ANY remaining missing value
      if (missing_st == "exclude") {
        keep <- complete.cases(mat)
        if (!all(keep)) {
          mat <- mat[keep, , drop = FALSE]
          # Trim self$data rows correspondingly (used later for idCol/response)
          # We store the keep mask so downstream code can slice self$data.
          private$.keepMask <- keep
        }
      } else {
        private$.keepMask <- rep(TRUE, nrow(self$data))
      }

      mat
    },


    # ════════════════════════════════════════════════════════════════════════
    # Output-filling helpers
    # ════════════════════════════════════════════════════════════════════════

    .fillSnpGridTable = function(wtable) {
      tbl <- self$results$snpGridTable
      tbl$deleteRows()
      inData     <- names(self$data)
      weightMode <- self$options$weightMode
      for (i in seq_len(nrow(wtable))) {
        r <- wtable[i, ]
        w <- if (weightMode == "equal") 1
             else if (is.na(r$effect_weight)) NA_real_
             else r$effect_weight
        tbl$addRow(rowKey = i, values = list(
          rsid          = r$rsid,
          chr           = r$chr,
          pos           = r$pos,
          effect_allele = r$effect_allele,
          other_allele  = r$other_allele,
          effect_weight = w,
          matched       = if (r$rsid %in% inData) "\u2713" else "\u2717"
        ))
      }
    },

    .fillCoverageTable = function(snpCols, wtable, missing_st, weightMode) {
      inData    <- names(self$data)
      matched   <- intersect(wtable$rsid, inData)
      ambiguous <- sum(private$.isAmbiguous(wtable$effect_allele, wtable$other_allele))

      # Pull metadata: from wtable attribute (file-parsed) or from cached grid option
      meta <- attr(wtable, "pgs_meta") %||%
              list(pgs_id = "", pgs_name = "", trait_reported = "",
                   weight_type = "", genome_build = "", variants_number = "")

      self$results$coverageTable$setRow(rowNo = 1, values = list(
        pgs_id         = meta$pgs_id         %||% "",
        pgs_name       = meta$pgs_name       %||% "",
        trait_reported = meta$trait_reported %||% "",
        weight_type    = meta$weight_type    %||% "",
        genome_build   = meta$genome_build   %||% "",
        snpsInWeights  = nrow(wtable),
        snpsInData     = length(intersect(snpCols, inData)),
        snpsMatched    = length(matched),
        pctMatched     = if (nrow(wtable) > 0) length(matched) / nrow(wtable) else 0,
        snpsAmbiguous  = ambiguous,
        missingStrategy = missing_st,
        weightMode      = weightMode
      ))
    },

    .isAmbiguous = function(ea, oa) {
      pairs <- paste0(toupper(ea), toupper(oa))
      pairs %in% c("AT", "TA", "CG", "GC")
    },

    .fillSummaryTable = function(scores) {
      e1071_skew <- tryCatch(
        e1071::skewness(scores, na.rm = TRUE),
        error = function(e) {
          n  <- sum(!is.na(scores))
          mu <- mean(scores, na.rm = TRUE)
          s  <- sd(scores, na.rm = TRUE)
          if (s == 0 || n < 3) return(NA_real_)
          sum(((scores[!is.na(scores)] - mu) / s)^3) * n / ((n-1)*(n-2))
        }
      )
      self$results$summaryTable$setRow(rowNo = 1, values = list(
        n    = sum(!is.na(scores)),
        mean = mean(scores, na.rm = TRUE),
        sd   = sd(scores,   na.rm = TRUE),
        min  = min(scores,  na.rm = TRUE),
        max  = max(scores,  na.rm = TRUE),
        skew = e1071_skew
      ))
    },

    .fillScoreTable = function(scores, ids) {
      tbl <- self$results$scoreTable
      tbl$deleteRows()
      mu  <- mean(scores, na.rm = TRUE)
      sig <- sd(scores, na.rm = TRUE)
      for (i in seq_along(scores)) {
        z   <- if (!is.na(sig) && sig > 0) (scores[i] - mu) / sig else NA_real_
        pct <- if (!is.na(scores[i])) mean(scores <= scores[i], na.rm = TRUE) * 100 else NA_real_
        tbl$addRow(rowKey = i, values = list(
          individual = ids[i],
          pgs        = scores[i],
          pgs_z      = z,
          percentile = pct
        ))
      }
    },

    .fillPercentileTable = function(scores) {
      breaks_str <- trimws(self$options$percentileBreaks)
      breaks_num <- suppressWarnings(as.numeric(strsplit(breaks_str, ",")[[1]]))
      breaks_num <- breaks_num[!is.na(breaks_num) & breaks_num >= 0 & breaks_num <= 100]
      if (length(breaks_num) == 0) breaks_num <- c(20, 40, 60, 80, 90, 95)

      tbl <- self$results$percentileTable
      tbl$deleteRows()
      for (b in breaks_num) {
        tbl$addRow(rowKey = b, values = list(
          threshold = paste0("P", b),
          score     = quantile(scores, b / 100, na.rm = TRUE)
        ))
      }
    },

    .fillAssocTable = function(scores, respCol) {
      if (!(respCol %in% names(self$data))) return()

      resp <- self$data[[respCol]]
      if (!is.null(private$.keepMask)) resp <- resp[private$.keepMask]

      df_assoc <- data.frame(pgs = scores, resp = resp)
      df_assoc <- df_assoc[complete.cases(df_assoc), ]
      if (nrow(df_assoc) < 3) return()

      is_binary <- is.factor(df_assoc$resp) ||
                   (length(unique(df_assoc$resp)) == 2 &&
                    all(df_assoc$resp %in% c(0, 1, NA)))

      fit <- tryCatch({
        if (is_binary) {
          glm(resp ~ pgs, data = df_assoc, family = binomial())
        } else {
          lm(resp ~ pgs, data = df_assoc)
        }
      }, error = function(e) NULL)

      if (is.null(fit)) return()

      sm    <- summary(fit)
      coefs <- coef(sm)
      if (nrow(coefs) < 2) return()

      beta <- coefs[2, 1]
      se   <- coefs[2, 2]
      stat <- coefs[2, 3]
      p    <- coefs[2, 4]

      self$results$assocTable$setRow(rowNo = 1, values = list(
        responseVar = respCol,
        model       = if (is_binary) "Logistic" else "Linear",
        beta        = beta,
        se          = se,
        stat        = stat,
        p           = p
      ))
    },


    # ════════════════════════════════════════════════════════════════════════
    # .plotDist  — render function for the distPlot Image result
    # ════════════════════════════════════════════════════════════════════════
    .plotDist = function(image, ...) {
      scores <- private$.pgsScores
      if (is.null(scores) || length(scores) < 2) return(FALSE)

      weightMode <- self$options$weightMode
      title_suffix <- if (weightMode == "equal") " (equal weights)" else " (catalog weights)"

      # ── Base R plot: histogram + density overlay ─────────────────────────
      opar <- par(no.readonly = TRUE)
      on.exit(par(opar))

      par(mar = c(4.5, 4.5, 3, 1.5), bg = "white")

      dens  <- density(scores, na.rm = TRUE)
      h     <- hist(scores, plot = FALSE, breaks = "Sturges")
      y_max <- max(max(h$density), max(dens$y)) * 1.15

      hist(scores,
           freq     = FALSE,
           breaks   = "Sturges",
           col      = "#AED6F1",
           border   = "#2980B9",
           main     = paste0("PGS Distribution", title_suffix),
           xlab     = "PGS Score",
           ylab     = "Density",
           ylim     = c(0, y_max),
           las      = 1)

      lines(dens, col = "#C0392B", lwd = 2.5)

      # Mean line
      abline(v = mean(scores, na.rm = TRUE),
             col = "#27AE60", lwd = 2, lty = 2)

      legend("topright",
             legend = c("Density", "Mean"),
             col    = c("#C0392B", "#27AE60"),
             lty    = c(1, 2),
             lwd    = 2,
             bty    = "n",
             cex    = 0.85)

      TRUE
    },

    # internal field: which individuals survive the "exclude" filter
    .keepMask = NULL
  )  # end private
)

# ── Null-coalescing helper ────────────────────────────────────────────────────
`%||%` <- function(a, b) if (!is.null(a)) a else b
