
# This file is automatically generated, you probably don't want to edit this

snpStatsOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpStatsOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            response = NULL,
            snps = NULL,
            covariates = NULL,
            responseType = "auto",
            subpop = FALSE,
            covDesc = FALSE,
            rmSnpMissing = FALSE,
            snpSummary = TRUE,
            allFreq = FALSE,
            genoFreq = FALSE,
            hweTest = FALSE,
            showMissing = FALSE,
            showMissingnessPlot = FALSE,
            missingnessThreshold = 0.1,
            snpAssoc = TRUE,
            modelCodominant = TRUE,
            modelDominant = FALSE,
            modelRecessive = FALSE,
            modelOverdominant = FALSE,
            modelLogAdditive = FALSE,
            ciWidth = 95,
            showAIC = FALSE,
            snpInteraction = FALSE,
            interactionType = "multiplicative",
            showInteractionTable = TRUE,
            showInteractionAdjVars = FALSE,
            showStratByCovariate = FALSE,
            showStratByGenotype = FALSE,
            showCrossClassTable = FALSE,
            ldAnalysis = FALSE,
            ldMatrix = FALSE,
            ldMetric = "r2",
            ldPlot = FALSE,
            haploFreq = FALSE,
            haploFreqMin = 0.01,
            ldSubpop = FALSE,
            haploAssoc = FALSE,
            haploInteraction = FALSE, ...) {

            super$initialize(
                package="SNPstats",
                name="snpStats",
                requiresData=TRUE,
                ...)

            private$..response <- jmvcore::OptionVariable$new(
                "response",
                response,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"),
                default=NULL)
            private$..snps <- jmvcore::OptionVariables$new(
                "snps",
                snps,
                suggested=list(
                    "nominal"),
                permitted=list(
                    "factor",
                    "id"))
            private$..covariates <- jmvcore::OptionVariables$new(
                "covariates",
                covariates,
                suggested=list(
                    "nominal",
                    "continuous"),
                permitted=list(
                    "factor",
                    "numeric"),
                default=NULL)
            private$..responseType <- jmvcore::OptionList$new(
                "responseType",
                responseType,
                options=list(
                    "auto",
                    "binary",
                    "quantitative",
                    "categorical"),
                default="auto")
            private$..subpop <- jmvcore::OptionBool$new(
                "subpop",
                subpop,
                default=FALSE)
            private$..covDesc <- jmvcore::OptionBool$new(
                "covDesc",
                covDesc,
                default=FALSE)
            private$..rmSnpMissing <- jmvcore::OptionBool$new(
                "rmSnpMissing",
                rmSnpMissing,
                default=FALSE)
            private$..snpSummary <- jmvcore::OptionBool$new(
                "snpSummary",
                snpSummary,
                default=TRUE)
            private$..allFreq <- jmvcore::OptionBool$new(
                "allFreq",
                allFreq,
                default=FALSE)
            private$..genoFreq <- jmvcore::OptionBool$new(
                "genoFreq",
                genoFreq,
                default=FALSE)
            private$..hweTest <- jmvcore::OptionBool$new(
                "hweTest",
                hweTest,
                default=FALSE)
            private$..showMissing <- jmvcore::OptionBool$new(
                "showMissing",
                showMissing,
                default=FALSE)
            private$..showMissingnessPlot <- jmvcore::OptionBool$new(
                "showMissingnessPlot",
                showMissingnessPlot,
                default=FALSE)
            private$..missingnessThreshold <- jmvcore::OptionNumber$new(
                "missingnessThreshold",
                missingnessThreshold,
                min=0,
                max=100,
                default=0.1)
            private$..snpAssoc <- jmvcore::OptionBool$new(
                "snpAssoc",
                snpAssoc,
                default=TRUE)
            private$..modelCodominant <- jmvcore::OptionBool$new(
                "modelCodominant",
                modelCodominant,
                default=TRUE)
            private$..modelDominant <- jmvcore::OptionBool$new(
                "modelDominant",
                modelDominant,
                default=FALSE)
            private$..modelRecessive <- jmvcore::OptionBool$new(
                "modelRecessive",
                modelRecessive,
                default=FALSE)
            private$..modelOverdominant <- jmvcore::OptionBool$new(
                "modelOverdominant",
                modelOverdominant,
                default=FALSE)
            private$..modelLogAdditive <- jmvcore::OptionBool$new(
                "modelLogAdditive",
                modelLogAdditive,
                default=FALSE)
            private$..ciWidth <- jmvcore::OptionNumber$new(
                "ciWidth",
                ciWidth,
                min=50,
                max=99.9,
                default=95)
            private$..showAIC <- jmvcore::OptionBool$new(
                "showAIC",
                showAIC,
                default=FALSE)
            private$..snpInteraction <- jmvcore::OptionBool$new(
                "snpInteraction",
                snpInteraction,
                default=FALSE)
            private$..interactionType <- jmvcore::OptionList$new(
                "interactionType",
                interactionType,
                options=list(
                    "multiplicative",
                    "conditional_on_covar",
                    "conditional_on_snp"),
                default="multiplicative")
            private$..showInteractionTable <- jmvcore::OptionBool$new(
                "showInteractionTable",
                showInteractionTable,
                default=TRUE)
            private$..showInteractionAdjVars <- jmvcore::OptionBool$new(
                "showInteractionAdjVars",
                showInteractionAdjVars,
                default=FALSE)
            private$..showStratByCovariate <- jmvcore::OptionBool$new(
                "showStratByCovariate",
                showStratByCovariate,
                default=FALSE)
            private$..showStratByGenotype <- jmvcore::OptionBool$new(
                "showStratByGenotype",
                showStratByGenotype,
                default=FALSE)
            private$..showCrossClassTable <- jmvcore::OptionBool$new(
                "showCrossClassTable",
                showCrossClassTable,
                default=FALSE)
            private$..ldAnalysis <- jmvcore::OptionBool$new(
                "ldAnalysis",
                ldAnalysis,
                default=FALSE)
            private$..ldMatrix <- jmvcore::OptionBool$new(
                "ldMatrix",
                ldMatrix,
                default=FALSE)
            private$..ldMetric <- jmvcore::OptionList$new(
                "ldMetric",
                ldMetric,
                options=list(
                    "r2",
                    "Dprime",
                    "D"),
                default="r2")
            private$..ldPlot <- jmvcore::OptionBool$new(
                "ldPlot",
                ldPlot,
                default=FALSE)
            private$..haploFreq <- jmvcore::OptionBool$new(
                "haploFreq",
                haploFreq,
                default=FALSE)
            private$..haploFreqMin <- jmvcore::OptionNumber$new(
                "haploFreqMin",
                haploFreqMin,
                min=0,
                max=0.5,
                default=0.01)
            private$..ldSubpop <- jmvcore::OptionBool$new(
                "ldSubpop",
                ldSubpop,
                default=FALSE)
            private$..haploAssoc <- jmvcore::OptionBool$new(
                "haploAssoc",
                haploAssoc,
                default=FALSE)
            private$..haploInteraction <- jmvcore::OptionBool$new(
                "haploInteraction",
                haploInteraction,
                default=FALSE)

            self$.addOption(private$..response)
            self$.addOption(private$..snps)
            self$.addOption(private$..covariates)
            self$.addOption(private$..responseType)
            self$.addOption(private$..subpop)
            self$.addOption(private$..covDesc)
            self$.addOption(private$..rmSnpMissing)
            self$.addOption(private$..snpSummary)
            self$.addOption(private$..allFreq)
            self$.addOption(private$..genoFreq)
            self$.addOption(private$..hweTest)
            self$.addOption(private$..showMissing)
            self$.addOption(private$..showMissingnessPlot)
            self$.addOption(private$..missingnessThreshold)
            self$.addOption(private$..snpAssoc)
            self$.addOption(private$..modelCodominant)
            self$.addOption(private$..modelDominant)
            self$.addOption(private$..modelRecessive)
            self$.addOption(private$..modelOverdominant)
            self$.addOption(private$..modelLogAdditive)
            self$.addOption(private$..ciWidth)
            self$.addOption(private$..showAIC)
            self$.addOption(private$..snpInteraction)
            self$.addOption(private$..interactionType)
            self$.addOption(private$..showInteractionTable)
            self$.addOption(private$..showInteractionAdjVars)
            self$.addOption(private$..showStratByCovariate)
            self$.addOption(private$..showStratByGenotype)
            self$.addOption(private$..showCrossClassTable)
            self$.addOption(private$..ldAnalysis)
            self$.addOption(private$..ldMatrix)
            self$.addOption(private$..ldMetric)
            self$.addOption(private$..ldPlot)
            self$.addOption(private$..haploFreq)
            self$.addOption(private$..haploFreqMin)
            self$.addOption(private$..ldSubpop)
            self$.addOption(private$..haploAssoc)
            self$.addOption(private$..haploInteraction)
        }),
    active = list(
        response = function() private$..response$value,
        snps = function() private$..snps$value,
        covariates = function() private$..covariates$value,
        responseType = function() private$..responseType$value,
        subpop = function() private$..subpop$value,
        covDesc = function() private$..covDesc$value,
        rmSnpMissing = function() private$..rmSnpMissing$value,
        snpSummary = function() private$..snpSummary$value,
        allFreq = function() private$..allFreq$value,
        genoFreq = function() private$..genoFreq$value,
        hweTest = function() private$..hweTest$value,
        showMissing = function() private$..showMissing$value,
        showMissingnessPlot = function() private$..showMissingnessPlot$value,
        missingnessThreshold = function() private$..missingnessThreshold$value,
        snpAssoc = function() private$..snpAssoc$value,
        modelCodominant = function() private$..modelCodominant$value,
        modelDominant = function() private$..modelDominant$value,
        modelRecessive = function() private$..modelRecessive$value,
        modelOverdominant = function() private$..modelOverdominant$value,
        modelLogAdditive = function() private$..modelLogAdditive$value,
        ciWidth = function() private$..ciWidth$value,
        showAIC = function() private$..showAIC$value,
        snpInteraction = function() private$..snpInteraction$value,
        interactionType = function() private$..interactionType$value,
        showInteractionTable = function() private$..showInteractionTable$value,
        showInteractionAdjVars = function() private$..showInteractionAdjVars$value,
        showStratByCovariate = function() private$..showStratByCovariate$value,
        showStratByGenotype = function() private$..showStratByGenotype$value,
        showCrossClassTable = function() private$..showCrossClassTable$value,
        ldAnalysis = function() private$..ldAnalysis$value,
        ldMatrix = function() private$..ldMatrix$value,
        ldMetric = function() private$..ldMetric$value,
        ldPlot = function() private$..ldPlot$value,
        haploFreq = function() private$..haploFreq$value,
        haploFreqMin = function() private$..haploFreqMin$value,
        ldSubpop = function() private$..ldSubpop$value,
        haploAssoc = function() private$..haploAssoc$value,
        haploInteraction = function() private$..haploInteraction$value),
    private = list(
        ..response = NA,
        ..snps = NA,
        ..covariates = NA,
        ..responseType = NA,
        ..subpop = NA,
        ..covDesc = NA,
        ..rmSnpMissing = NA,
        ..snpSummary = NA,
        ..allFreq = NA,
        ..genoFreq = NA,
        ..hweTest = NA,
        ..showMissing = NA,
        ..showMissingnessPlot = NA,
        ..missingnessThreshold = NA,
        ..snpAssoc = NA,
        ..modelCodominant = NA,
        ..modelDominant = NA,
        ..modelRecessive = NA,
        ..modelOverdominant = NA,
        ..modelLogAdditive = NA,
        ..ciWidth = NA,
        ..showAIC = NA,
        ..snpInteraction = NA,
        ..interactionType = NA,
        ..showInteractionTable = NA,
        ..showInteractionAdjVars = NA,
        ..showStratByCovariate = NA,
        ..showStratByGenotype = NA,
        ..showCrossClassTable = NA,
        ..ldAnalysis = NA,
        ..ldMatrix = NA,
        ..ldMetric = NA,
        ..ldPlot = NA,
        ..haploFreq = NA,
        ..haploFreqMin = NA,
        ..ldSubpop = NA,
        ..haploAssoc = NA,
        ..haploInteraction = NA)
)

snpStatsResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpStatsResults",
    inherit = jmvcore::Group,
    active = list(
        validationMsg = function() private$.items[["validationMsg"]],
        descGroup = function() private$.items[["descGroup"]],
        assocGroup = function() private$.items[["assocGroup"]],
        ldHaploGroup = function() private$.items[["ldHaploGroup"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="SNP Analysis",
                refs=list(
                    "snpstats",
                    "bioinfo"))
            self$add(jmvcore::Html$new(
                options=options,
                name="validationMsg",
                title="",
                visible=FALSE))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    validationMsgSNP = function() private$.items[["validationMsgSNP"]],
                    validationMsgGeno = function() private$.items[["validationMsgGeno"]],
                    covDescGroup = function() private$.items[["covDescGroup"]],
                    snpSummaryTablesGroup = function() private$.items[["snpSummaryTablesGroup"]],
                    descSnpResults = function() private$.items[["descSnpResults"]],
                    missingnessPlot = function() private$.items[["missingnessPlot"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="descGroup",
                            title="Descriptive")
                        self$add(jmvcore::Html$new(
                            options=options,
                            name="validationMsgSNP",
                            title="",
                            visible=FALSE))
                        self$add(jmvcore::Html$new(
                            options=options,
                            name="validationMsgGeno",
                            title="",
                            visible=FALSE))
                        self$add(R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                covDescTable = function() private$.items[["covDescTable"]]),
                            private = list(),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="covDescGroup",
                                        title="Covariate Descriptives")
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="covDescTable",
                                        title="Covariate Summary",
                                        columns=list(
                                            list(
                                                `name`="variable", 
                                                `title`="Variable", 
                                                `type`="text"),
                                            list(
                                                `name`="level", 
                                                `title`="Level", 
                                                `type`="text"),
                                            list(
                                                `name`="stat_overall", 
                                                `title`="Overall", 
                                                `type`="text"),
                                            list(
                                                `name`="stat_g0", 
                                                `title`="Group 0", 
                                                `type`="text", 
                                                `visible`=FALSE),
                                            list(
                                                `name`="stat_g1", 
                                                `title`="Group 1", 
                                                `type`="text", 
                                                `visible`=FALSE),
                                            list(
                                                `name`="stat_g2", 
                                                `title`="Group 2", 
                                                `type`="text", 
                                                `visible`=FALSE),
                                            list(
                                                `name`="stat_g3", 
                                                `title`="Group 3", 
                                                `type`="text", 
                                                `visible`=FALSE),
                                            list(
                                                `name`="stat_g4", 
                                                `title`="Group 4", 
                                                `type`="text", 
                                                `visible`=FALSE),
                                            list(
                                                `name`="stat_g5", 
                                                `title`="Group 5", 
                                                `type`="text", 
                                                `visible`=FALSE),
                                            list(
                                                `name`="stat_g6", 
                                                `title`="Group 6", 
                                                `type`="text", 
                                                `visible`=FALSE),
                                            list(
                                                `name`="stat_g7", 
                                                `title`="Group 7", 
                                                `type`="text", 
                                                `visible`=FALSE),
                                            list(
                                                `name`="pval", 
                                                `title`="P-value", 
                                                `type`="number", 
                                                `format`="zto", 
                                                `visible`=FALSE))))}))$new(options=options))
                        self$add(R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                snpSummaryTable = function() private$.items[["snpSummaryTable"]]),
                            private = list(),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="snpSummaryTablesGroup",
                                        title="SNP Descriptive")
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="snpSummaryTable",
                                        title="SNP Summary Table",
                                        visible="(snpSummary)",
                                        columns=list(
                                            list(
                                                `name`="snp", 
                                                `title`="SNP", 
                                                `type`="text"),
                                            list(
                                                `name`="alleles", 
                                                `title`="Alleles (A/B)", 
                                                `type`="text"),
                                            list(
                                                `name`="group", 
                                                `title`="Group", 
                                                `type`="text"),
                                            list(
                                                `name`="n", 
                                                `title`="N", 
                                                `type`="integer"),
                                            list(
                                                `name`="missing", 
                                                `title`="Missing", 
                                                `type`="integer"),
                                            list(
                                                `name`="maf", 
                                                `title`="MAF (B)", 
                                                `type`="number", 
                                                `format`="zto"),
                                            list(
                                                `name`="genoCounts", 
                                                `title`="AA / AB / BB", 
                                                `type`="text"),
                                            list(
                                                `name`="hwePval", 
                                                `title`="HWE p-value", 
                                                `type`="number", 
                                                `format`="zto"))))}))$new(options=options))
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="descSnpResults",
                            title="SNP Results",
                            template=R6::R6Class(
                                inherit = jmvcore::Group,
                                active = list(
                                    typingRate = function() private$.items[["typingRate"]],
                                    allFreqTable = function() private$.items[["allFreqTable"]],
                                    genoFreqTable = function() private$.items[["genoFreqTable"]],
                                    hweTable = function() private$.items[["hweTable"]]),
                                private = list(),
                                public=list(
                                    initialize=function(options) {
                                        super$initialize(
                                            options=options,
                                            name="undefined",
                                            title="$key")
                                        self$add(jmvcore::Html$new(
                                            options=options,
                                            name="typingRate",
                                            title="",
                                            visible="(allFreq || genoFreq || hweTest)"))
                                        self$add(jmvcore::Table$new(
                                            options=options,
                                            name="allFreqTable",
                                            title="Allele Frequencies",
                                            visible="(allFreq)",
                                            columns=list(
                                                list(
                                                    `name`="allele", 
                                                    `title`="Allele", 
                                                    `type`="text"),
                                                list(
                                                    `name`="stat", 
                                                    `title`="N (%)", 
                                                    `type`="text"))))
                                        self$add(jmvcore::Table$new(
                                            options=options,
                                            name="genoFreqTable",
                                            title="Genotype Frequencies",
                                            visible="(genoFreq)",
                                            columns=list(
                                                list(
                                                    `name`="genotype", 
                                                    `title`="Genotype", 
                                                    `type`="text"),
                                                list(
                                                    `name`="stat", 
                                                    `title`="N (%)", 
                                                    `type`="text"),
                                                list(
                                                    `name`="responseStat", 
                                                    `title`="Response (mean\u00B1SE)", 
                                                    `type`="text", 
                                                    `visible`=FALSE))))
                                        self$add(jmvcore::Table$new(
                                            options=options,
                                            name="hweTable",
                                            title="Hardy-Weinberg Equilibrium",
                                            visible="(hweTest)",
                                            columns=list(
                                                list(
                                                    `name`="group", 
                                                    `title`="Group", 
                                                    `type`="text"),
                                                list(
                                                    `name`="n11", 
                                                    `title`="AA", 
                                                    `type`="integer"),
                                                list(
                                                    `name`="n12", 
                                                    `title`="AB", 
                                                    `type`="integer"),
                                                list(
                                                    `name`="n22", 
                                                    `title`="BB", 
                                                    `type`="integer"),
                                                list(
                                                    `name`="missing", 
                                                    `title`="Missing", 
                                                    `type`="integer", 
                                                    `visible`=FALSE),
                                                list(
                                                    `name`="pval", 
                                                    `title`="P-value", 
                                                    `type`="number", 
                                                    `format`="zto"))))}))$new(options=options)))
                        self$add(jmvcore::Image$new(
                            options=options,
                            name="missingnessPlot",
                            title="SNP Missingness",
                            visible=FALSE,
                            width=560,
                            height=500,
                            renderFun=".plotMissingness",
                            clearWith=list(
                                "snps",
                                "response",
                                "covariates",
                                "subpop",
                                "missingnessThreshold")))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    assocSnpResults = function() private$.items[["assocSnpResults"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="assocGroup",
                            title="Association")
                        self$add(jmvcore::Array$new(
                            options=options,
                            name="assocSnpResults",
                            title="SNP Association Results",
                            template=R6::R6Class(
                                inherit = jmvcore::Group,
                                active = list(
                                    typingRate = function() private$.items[["typingRate"]],
                                    assocTable = function() private$.items[["assocTable"]],
                                    interactionResults = function() private$.items[["interactionResults"]]),
                                private = list(),
                                public=list(
                                    initialize=function(options) {
                                        super$initialize(
                                            options=options,
                                            name="undefined",
                                            title="$key")
                                        self$add(jmvcore::Html$new(
                                            options=options,
                                            name="typingRate",
                                            title="",
                                            visible=TRUE))
                                        self$add(jmvcore::Table$new(
                                            options=options,
                                            name="assocTable",
                                            title="Association with Response",
                                            visible="(snpAssoc && (modelCodominant || modelDominant || modelRecessive || modelOverdominant || modelLogAdditive))",
                                            columns=list(
                                                list(
                                                    `name`="model", 
                                                    `title`="Model", 
                                                    `type`="text"),
                                                list(
                                                    `name`="genotype", 
                                                    `title`="Genotype", 
                                                    `type`="text"),
                                                list(
                                                    `name`="stat0", 
                                                    `title`="Group 0", 
                                                    `type`="text"),
                                                list(
                                                    `name`="stat1", 
                                                    `title`="Group 1", 
                                                    `type`="text"),
                                                list(
                                                    `name`="effect", 
                                                    `title`="OR / \u03B2", 
                                                    `type`="number", 
                                                    `format`="zto"),
                                                list(
                                                    `name`="ciLow", 
                                                    `title`="Lower CI", 
                                                    `type`="number", 
                                                    `format`="zto"),
                                                list(
                                                    `name`="ciHigh", 
                                                    `title`="Upper CI", 
                                                    `type`="number", 
                                                    `format`="zto"),
                                                list(
                                                    `name`="pval", 
                                                    `title`="P-value", 
                                                    `type`="number", 
                                                    `format`="zto"),
                                                list(
                                                    `name`="AIC", 
                                                    `title`="AIC", 
                                                    `type`="number", 
                                                    `format`="zto", 
                                                    `visible`=FALSE),
                                                list(
                                                    `name`="BIC", 
                                                    `title`="BIC", 
                                                    `type`="number", 
                                                    `format`="zto", 
                                                    `visible`=FALSE))))
                                        self$add(jmvcore::Array$new(
                                            options=options,
                                            name="interactionResults",
                                            title="Interaction Results",
                                            visible="(snpInteraction)",
                                            template=R6::R6Class(
                                                inherit = jmvcore::Group,
                                                active = list(
                                                    interactionTable = function() private$.items[["interactionTable"]],
                                                    stratByCovariateHeading = function() private$.items[["stratByCovariateHeading"]],
                                                    stratByCovariate = function() private$.items[["stratByCovariate"]],
                                                    stratByGenotypeHeading = function() private$.items[["stratByGenotypeHeading"]],
                                                    stratByGenotype = function() private$.items[["stratByGenotype"]],
                                                    crossClassHeading = function() private$.items[["crossClassHeading"]],
                                                    crossClassTable = function() private$.items[["crossClassTable"]]),
                                                private = list(),
                                                public=list(
                                                    initialize=function(options) {
                                                        super$initialize(
                                                            options=options,
                                                            name="undefined",
                                                            title="$key")
                                                        self$add(jmvcore::Table$new(
                                                            options=options,
                                                            name="interactionTable",
                                                            title="SNP \u00D7 Covariate Interaction",
                                                            visible="(snpInteraction && showInteractionTable)",
                                                            columns=list(
                                                                list(
                                                                    `name`="model", 
                                                                    `title`="Model", 
                                                                    `type`="text"),
                                                                list(
                                                                    `name`="term", 
                                                                    `title`="Term", 
                                                                    `type`="text"),
                                                                list(
                                                                    `name`="effect", 
                                                                    `title`="OR / \u03B2", 
                                                                    `type`="number", 
                                                                    `format`="zto"),
                                                                list(
                                                                    `name`="ciLow", 
                                                                    `title`="Lower CI", 
                                                                    `type`="number", 
                                                                    `format`="zto"),
                                                                list(
                                                                    `name`="ciHigh", 
                                                                    `title`="Upper CI", 
                                                                    `type`="number", 
                                                                    `format`="zto"),
                                                                list(
                                                                    `name`="pval", 
                                                                    `title`="P-value", 
                                                                    `type`="number", 
                                                                    `format`="zto"),
                                                                list(
                                                                    `name`="AIC", 
                                                                    `title`="AIC", 
                                                                    `type`="number", 
                                                                    `format`="zto", 
                                                                    `visible`=FALSE),
                                                                list(
                                                                    `name`="BIC", 
                                                                    `title`="BIC", 
                                                                    `type`="number", 
                                                                    `format`="zto", 
                                                                    `visible`=FALSE))))
                                                        self$add(jmvcore::Html$new(
                                                            options=options,
                                                            name="stratByCovariateHeading",
                                                            title="",
                                                            visible="(snpInteraction && showStratByCovariate)"))
                                                        self$add(jmvcore::Array$new(
                                                            options=options,
                                                            name="stratByCovariate",
                                                            title="",
                                                            visible="(snpInteraction && showStratByCovariate)",
                                                            template=jmvcore::Table$new(
                                                                options=options,
                                                                title="$key",
                                                                columns=list(
                                                                    list(
                                                                        `name`="genotype", 
                                                                        `title`="Genotype", 
                                                                        `type`="text"),
                                                                    list(
                                                                        `name`="stat0", 
                                                                        `title`="Group 0", 
                                                                        `type`="text"),
                                                                    list(
                                                                        `name`="stat1", 
                                                                        `title`="Group 1", 
                                                                        `type`="text"),
                                                                    list(
                                                                        `name`="effect", 
                                                                        `title`="OR / \u03B2", 
                                                                        `type`="number", 
                                                                        `format`="zto"),
                                                                    list(
                                                                        `name`="ciLow", 
                                                                        `title`="Lower CI", 
                                                                        `type`="number", 
                                                                        `format`="zto"),
                                                                    list(
                                                                        `name`="ciHigh", 
                                                                        `title`="Upper CI", 
                                                                        `type`="number", 
                                                                        `format`="zto"),
                                                                    list(
                                                                        `name`="pval", 
                                                                        `title`="P-value", 
                                                                        `type`="number", 
                                                                        `format`="zto")))))
                                                        self$add(jmvcore::Html$new(
                                                            options=options,
                                                            name="stratByGenotypeHeading",
                                                            title="",
                                                            visible="(snpInteraction && showStratByGenotype)"))
                                                        self$add(jmvcore::Array$new(
                                                            options=options,
                                                            name="stratByGenotype",
                                                            title="",
                                                            visible="(snpInteraction && showStratByGenotype)",
                                                            template=jmvcore::Table$new(
                                                                options=options,
                                                                title="$key",
                                                                columns=list(
                                                                    list(
                                                                        `name`="level", 
                                                                        `title`="Level", 
                                                                        `type`="text"),
                                                                    list(
                                                                        `name`="stat0", 
                                                                        `title`="Group 0", 
                                                                        `type`="text"),
                                                                    list(
                                                                        `name`="stat1", 
                                                                        `title`="Group 1", 
                                                                        `type`="text"),
                                                                    list(
                                                                        `name`="effect", 
                                                                        `title`="OR / \u03B2", 
                                                                        `type`="number", 
                                                                        `format`="zto"),
                                                                    list(
                                                                        `name`="ciLow", 
                                                                        `title`="Lower CI", 
                                                                        `type`="number", 
                                                                        `format`="zto"),
                                                                    list(
                                                                        `name`="ciHigh", 
                                                                        `title`="Upper CI", 
                                                                        `type`="number", 
                                                                        `format`="zto"),
                                                                    list(
                                                                        `name`="pval", 
                                                                        `title`="P-value", 
                                                                        `type`="number", 
                                                                        `format`="zto")))))
                                                        self$add(jmvcore::Html$new(
                                                            options=options,
                                                            name="crossClassHeading",
                                                            title="",
                                                            visible="(snpInteraction && showCrossClassTable)"))
                                                        self$add(jmvcore::Array$new(
                                                            options=options,
                                                            name="crossClassTable",
                                                            title="",
                                                            visible="(snpInteraction && showCrossClassTable)",
                                                            template=jmvcore::Table$new(
                                                                options=options,
                                                                title="$key",
                                                                columns=list(
                                                                    list(
                                                                        `name`="genotype", 
                                                                        `title`="Genotype", 
                                                                        `type`="text"),
                                                                    list(
                                                                        `name`="stat0", 
                                                                        `title`="Group 0", 
                                                                        `type`="text"),
                                                                    list(
                                                                        `name`="stat1", 
                                                                        `title`="Group 1", 
                                                                        `type`="text"),
                                                                    list(
                                                                        `name`="effect", 
                                                                        `title`="OR / \u03B2", 
                                                                        `type`="number", 
                                                                        `format`="zto"),
                                                                    list(
                                                                        `name`="ciLow", 
                                                                        `title`="Lower CI", 
                                                                        `type`="number", 
                                                                        `format`="zto"),
                                                                    list(
                                                                        `name`="ciHigh", 
                                                                        `title`="Upper CI", 
                                                                        `type`="number", 
                                                                        `format`="zto")))))}))$new(options=options)))}))$new(options=options)))}))$new(options=options))
            self$add(R6::R6Class(
                inherit = jmvcore::Group,
                active = list(
                    ldGroup = function() private$.items[["ldGroup"]],
                    haploGroup = function() private$.items[["haploGroup"]]),
                private = list(),
                public=list(
                    initialize=function(options) {
                        super$initialize(
                            options=options,
                            name="ldHaploGroup",
                            title="LD / Haplotype")
                        self$add(R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                ldTable = function() private$.items[["ldTable"]],
                                ldMatrixTable = function() private$.items[["ldMatrixTable"]],
                                ldPlotImage = function() private$.items[["ldPlotImage"]]),
                            private = list(),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="ldGroup",
                                        title="Linkage Disequilibrium")
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="ldTable",
                                        title="Pairwise LD",
                                        visible="(ldAnalysis)",
                                        columns=list(
                                            list(
                                                `name`="snp1", 
                                                `title`="SNP 1", 
                                                `type`="text"),
                                            list(
                                                `name`="snp2", 
                                                `title`="SNP 2", 
                                                `type`="text"),
                                            list(
                                                `name`="r2", 
                                                `title`="r\u00B2", 
                                                `type`="number", 
                                                `format`="zto"),
                                            list(
                                                `name`="Dprime", 
                                                `title`="D'", 
                                                `type`="number", 
                                                `format`="zto"),
                                            list(
                                                `name`="D", 
                                                `title`="D", 
                                                `type`="number", 
                                                `format`="zto"),
                                            list(
                                                `name`="pval", 
                                                `title`="P-value", 
                                                `type`="number", 
                                                `format`="zto"))))
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="ldMatrixTable",
                                        title="LD Matrix",
                                        visible="(ldMatrix)",
                                        columns=list(
                                            list(
                                                `name`="snp", 
                                                `title`="SNP", 
                                                `type`="text"))))
                                    self$add(jmvcore::Image$new(
                                        options=options,
                                        name="ldPlotImage",
                                        title="LD Heatmap",
                                        visible="(ldPlot)",
                                        renderFun=".render_ld_plot",
                                        width=500,
                                        height=450))}))$new(options=options))
                        self$add(R6::R6Class(
                            inherit = jmvcore::Group,
                            active = list(
                                haploFreqTable = function() private$.items[["haploFreqTable"]],
                                haploAssocTable = function() private$.items[["haploAssocTable"]],
                                haploInteractionTable = function() private$.items[["haploInteractionTable"]],
                                haploCondCovarTable = function() private$.items[["haploCondCovarTable"]],
                                haploCondHaploTable = function() private$.items[["haploCondHaploTable"]]),
                            private = list(),
                            public=list(
                                initialize=function(options) {
                                    super$initialize(
                                        options=options,
                                        name="haploGroup",
                                        title="Haplotype Analysis")
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="haploFreqTable",
                                        title="Haplotype Frequencies",
                                        visible="(haploFreq)",
                                        columns=list(
                                            list(
                                                `name`="haplotype", 
                                                `title`="Haplotype", 
                                                `type`="text"),
                                            list(
                                                `name`="freq", 
                                                `title`="Frequency", 
                                                `type`="number", 
                                                `format`="zto"),
                                            list(
                                                `name`="freq_g0", 
                                                `title`="Group 0", 
                                                `type`="number", 
                                                `format`="zto", 
                                                `visible`=FALSE),
                                            list(
                                                `name`="freq_g1", 
                                                `title`="Group 1", 
                                                `type`="number", 
                                                `format`="zto", 
                                                `visible`=FALSE))))
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="haploAssocTable",
                                        title="Haplotype Association",
                                        visible="(haploAssoc)",
                                        columns=list(
                                            list(
                                                `name`="haplotype", 
                                                `title`="Haplotype", 
                                                `type`="text"),
                                            list(
                                                `name`="freq", 
                                                `title`="Frequency", 
                                                `type`="number", 
                                                `format`="zto"),
                                            list(
                                                `name`="effect", 
                                                `title`="OR / \u03B2", 
                                                `type`="number"),
                                            list(
                                                `name`="ciLow", 
                                                `title`="Lower CI", 
                                                `type`="number"),
                                            list(
                                                `name`="ciHigh", 
                                                `title`="Upper CI", 
                                                `type`="number"),
                                            list(
                                                `name`="pval", 
                                                `title`="P-value", 
                                                `type`="number", 
                                                `format`="zto"))))
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="haploInteractionTable",
                                        title="Haplotype \u00D7 Covariate Interaction (cross-classification)",
                                        visible="(haploInteraction)",
                                        columns=list(
                                            list(
                                                `name`="term", 
                                                `title`="Haplotype", 
                                                `type`="text"),
                                            list(
                                                `name`="freq", 
                                                `title`="Frequency", 
                                                `type`="number", 
                                                `format`="zto"))))
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="haploCondCovarTable",
                                        title="Haplotype Effect within Covariate Levels",
                                        visible="(haploInteraction)",
                                        columns=list(
                                            list(
                                                `name`="term", 
                                                `title`="Haplotype", 
                                                `type`="text"),
                                            list(
                                                `name`="freq", 
                                                `title`="Frequency", 
                                                `type`="number", 
                                                `format`="zto"))))
                                    self$add(jmvcore::Table$new(
                                        options=options,
                                        name="haploCondHaploTable",
                                        title="Covariate Effect within Haplotypes",
                                        visible="(haploInteraction)",
                                        columns=list(
                                            list(
                                                `name`="term", 
                                                `title`="Haplotype", 
                                                `type`="text"),
                                            list(
                                                `name`="freq", 
                                                `title`="Frequency", 
                                                `type`="number", 
                                                `format`="zto"))))}))$new(options=options))}))$new(options=options))}))

snpStatsBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "snpStatsBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "SNPstats",
                name = "snpStats",
                version = c(0,1,0),
                options = options,
                results = snpStatsResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' SNP Analysis
#'
#' 
#' @param data [object Object]
#' @param response .
#' @param snps .
#' @param covariates .
#' @param responseType Controls how the response variable is treated.
#'   Auto-detect selects binary (2 levels), categorical (3-6 levels, factor), or
#'   quantitative (numeric). For categorical responses, association analysis
#'   uses multinomial logistic regression (nnet::multinom); SNP x covariate
#'   interaction and haplotype association are not available for categorical
#'   responses.
#' @param subpop .
#' @param covDesc .
#' @param rmSnpMissing .
#' @param snpSummary .
#' @param allFreq .
#' @param genoFreq .
#' @param hweTest .
#' @param showMissing .
#' @param showMissingnessPlot .
#' @param missingnessThreshold Only SNPs whose missing genotype percentage
#'   exceeds this value are displayed in the missingness plot. Set to 0 to show
#'   all SNPs.
#' @param snpAssoc .
#' @param modelCodominant .
#' @param modelDominant .
#' @param modelRecessive .
#' @param modelOverdominant .
#' @param modelLogAdditive .
#' @param ciWidth .
#' @param showAIC .
#' @param snpInteraction .
#' @param interactionType .
#' @param showInteractionTable .
#' @param showInteractionAdjVars .
#' @param showStratByCovariate .
#' @param showStratByGenotype .
#' @param showCrossClassTable .
#' @param ldAnalysis .
#' @param ldMatrix .
#' @param ldMetric .
#' @param ldPlot .
#' @param haploFreq .
#' @param haploFreqMin .
#' @param ldSubpop .
#' @param haploAssoc .
#' @param haploInteraction .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$validationMsg} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$descGroup$validationMsgSNP} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$descGroup$validationMsgGeno} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$descGroup$covDescGroup} \tab \tab \tab \tab \tab a group \cr
#'   \code{results$descGroup$snpSummaryTablesGroup} \tab \tab \tab \tab \tab a group \cr
#'   \code{results$descGroup$descSnpResults} \tab \tab \tab \tab \tab Per-SNP descriptive results \cr
#'   \code{results$descGroup$missingnessPlot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$assocGroup$assocSnpResults} \tab \tab \tab \tab \tab Per-SNP association results \cr
#'   \code{results$ldHaploGroup$ldGroup} \tab \tab \tab \tab \tab a group \cr
#'   \code{results$ldHaploGroup$haploGroup} \tab \tab \tab \tab \tab a group \cr
#' }
#'
#' @export
snpStats <- function(
    data,
    response = NULL,
    snps,
    covariates = NULL,
    responseType = "auto",
    subpop = FALSE,
    covDesc = FALSE,
    rmSnpMissing = FALSE,
    snpSummary = TRUE,
    allFreq = FALSE,
    genoFreq = FALSE,
    hweTest = FALSE,
    showMissing = FALSE,
    showMissingnessPlot = FALSE,
    missingnessThreshold = 0.1,
    snpAssoc = TRUE,
    modelCodominant = TRUE,
    modelDominant = FALSE,
    modelRecessive = FALSE,
    modelOverdominant = FALSE,
    modelLogAdditive = FALSE,
    ciWidth = 95,
    showAIC = FALSE,
    snpInteraction = FALSE,
    interactionType = "multiplicative",
    showInteractionTable = TRUE,
    showInteractionAdjVars = FALSE,
    showStratByCovariate = FALSE,
    showStratByGenotype = FALSE,
    showCrossClassTable = FALSE,
    ldAnalysis = FALSE,
    ldMatrix = FALSE,
    ldMetric = "r2",
    ldPlot = FALSE,
    haploFreq = FALSE,
    haploFreqMin = 0.01,
    ldSubpop = FALSE,
    haploAssoc = FALSE,
    haploInteraction = FALSE) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("snpStats requires jmvcore to be installed (restart may be required)")

    if ( ! missing(response)) response <- jmvcore::resolveQuo(jmvcore::enquo(response))
    if ( ! missing(snps)) snps <- jmvcore::resolveQuo(jmvcore::enquo(snps))
    if ( ! missing(covariates)) covariates <- jmvcore::resolveQuo(jmvcore::enquo(covariates))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(response), response, NULL),
            `if`( ! missing(snps), snps, NULL),
            `if`( ! missing(covariates), covariates, NULL))


    options <- snpStatsOptions$new(
        response = response,
        snps = snps,
        covariates = covariates,
        responseType = responseType,
        subpop = subpop,
        covDesc = covDesc,
        rmSnpMissing = rmSnpMissing,
        snpSummary = snpSummary,
        allFreq = allFreq,
        genoFreq = genoFreq,
        hweTest = hweTest,
        showMissing = showMissing,
        showMissingnessPlot = showMissingnessPlot,
        missingnessThreshold = missingnessThreshold,
        snpAssoc = snpAssoc,
        modelCodominant = modelCodominant,
        modelDominant = modelDominant,
        modelRecessive = modelRecessive,
        modelOverdominant = modelOverdominant,
        modelLogAdditive = modelLogAdditive,
        ciWidth = ciWidth,
        showAIC = showAIC,
        snpInteraction = snpInteraction,
        interactionType = interactionType,
        showInteractionTable = showInteractionTable,
        showInteractionAdjVars = showInteractionAdjVars,
        showStratByCovariate = showStratByCovariate,
        showStratByGenotype = showStratByGenotype,
        showCrossClassTable = showCrossClassTable,
        ldAnalysis = ldAnalysis,
        ldMatrix = ldMatrix,
        ldMetric = ldMetric,
        ldPlot = ldPlot,
        haploFreq = haploFreq,
        haploFreqMin = haploFreqMin,
        ldSubpop = ldSubpop,
        haploAssoc = haploAssoc,
        haploInteraction = haploInteraction)

    analysis <- snpStatsClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

